Repository fedspendingtransparency/usaspending-api, pull requests merged in 2020-11, with the labels that each got.

#2849 [DEV-6456] fixed columns in ES transactions ETL and renamed one in code
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/etl/management/commands/es_rapidloader.py
  usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
  usaspending_api/search/v2/elasticsearch_helper.py
Labels: hotfix

#2851 Master -> QAT
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/etl/management/commands/es_rapidloader.py
  usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
  usaspending_api/search/v2/elasticsearch_helper.py
Labels: down merge

#2852 QAT -> Dev
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/etl/management/commands/es_rapidloader.py
  usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
  usaspending_api/search/v2/elasticsearch_helper.py
Labels: down merge

#2855 [DEV-6457] Fix ES covid endpoint discrepancies
  usaspending_api/disaster/tests/integration/test_federal_account_award.py
  usaspending_api/disaster/tests/integration/test_federal_account_loans.py
  usaspending_api/disaster/tests/integration/test_object_class_spending_award.py
  usaspending_api/disaster/v2/views/agency/loans.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/elasticsearch_account_base.py
  usaspending_api/disaster/v2/views/federal_account/loans.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/object_class/loans.py
  usaspending_api/disaster/v2/views/object_class/spending.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_psc.py
  usaspending_api/search/tests/integration/test_spending_over_time.py
Labels: warmfix

#2856 [DEV-6471] Add ACL to boto3 upload args
  usaspending_api/common/helpers/s3_helpers.py
Labels: warmfix

#2857 Downmerge QAT -> DEV
  usaspending_api/common/helpers/s3_helpers.py
  usaspending_api/disaster/tests/integration/test_federal_account_award.py
  usaspending_api/disaster/tests/integration/test_federal_account_loans.py
  usaspending_api/disaster/tests/integration/test_object_class_spending_award.py
  usaspending_api/disaster/v2/views/agency/loans.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/elasticsearch_account_base.py
  usaspending_api/disaster/v2/views/federal_account/loans.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/object_class/loans.py
  usaspending_api/disaster/v2/views/object_class/spending.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_psc.py
  usaspending_api/search/tests/integration/test_spending_over_time.py
Labels: down merge

#2859 [DEV-6468] Update boto3 endpoint format for SQS
  usaspending_api/common/sqs/sqs_handler.py
  usaspending_api/common/tests/unit/test_sqs_work_dispatcher.py
Labels: warmfix

#2860 Downmerge QAT -> DEV
  usaspending_api/common/sqs/sqs_handler.py
  usaspending_api/common/tests/unit/test_sqs_work_dispatcher.py
Labels: down merge
