Repository fedspendingtransparency/usaspending-api, pull requests merged in 2020-02, with the labels that each got.

#2262 [DEV-4408] Changing unique field for new transaction loaders
  usaspending_api/transactions/agnostic_transaction_deletes.py
  usaspending_api/transactions/agnostic_transaction_loader.py
  usaspending_api/transactions/loader_functions.py
  usaspending_api/transactions/management/commands/transfer_assistance_records.py
  usaspending_api/transactions/management/commands/transfer_procurement_records.py
  usaspending_api/transactions/migrations/0001_initial.py
  usaspending_api/transactions/models/source_assistance_transaction.py
Labels: warmfix

#2268 [FIX] Updated Delta Download script fieldname
  usaspending_api/download/management/commands/populate_monthly_delta_files.py
Labels: hotfix

#2274 [DEV-3997 HOTFIX]: Temporarily remove account rollups
  usaspending_api/download/lookups.py
  usaspending_api/download/tests/integration/test_download_accounts_dev_3997.py
Labels: hotfix

#2282 [DEV-4408] Ignoring FABS duplicates from inactive records
  usaspending_api/common/etl/etl_dblink_table.py
  usaspending_api/transactions/agnostic_transaction_loader.py
  usaspending_api/transactions/management/commands/transfer_assistance_records.py
  usaspending_api/transactions/management/commands/transfer_procurement_records.py
  usaspending_api/transactions/tests/integration/test_assistance_etl.py
Labels: warmfix

#2293 [OPS-1096] Added chunking to submission loader
  usaspending_api/etl/management/commands/load_submission.py
  usaspending_api/etl/management/helpers/load_submission.py
Labels: warmfix

#2294 [FIX] Fixing ETL issues
  usaspending_api/etl/es_etl_helpers.py
  usaspending_api/etl/rapidloader.py
  usaspending_api/transactions/agnostic_transaction_deletes.py
  usaspending_api/transactions/management/commands/delete_assistance_records.py
Labels: hotfix

#2296 [OPS] Removing truncate from SQL scripts
  usaspending_api/broker/management/sql/restock_duns.sql
  usaspending_api/recipient/management/sql/restock_recipient_lookup.sql
  usaspending_api/recipient/management/sql/restock_recipient_profile.sql
  usaspending_api/recipient/management/sql/restock_summary_award_recipient.sql
Labels: warmfix

#2300 Fix JSON aggregation in award_delta_view
  usaspending_api/database_scripts/etl/award_delta_view.sql
Labels: hotfix

#2303 Check awards for deletes sql fix
  usaspending_api/etl/es_etl_helpers.py
  usaspending_api/etl/tests/test_es_rapidloader.py
Labels: hotfix

#2308 [DEV-3932] Adjust download agency list
  usaspending_api/api_contracts/contracts/v2/bulk_download/list_agencies.md
  usaspending_api/download/v2/download_list_agencies.py
Labels: paired with website PR

#2315 [DEV-3932] WARMFIX Subtier agency response typo
  usaspending_api/download/v2/download_list_agencies.py
Labels: warmfix

#2314 [FIX] SpendingByAward was unintentionally running an extra SQL
  usaspending_api/search/v2/views/spending_by_award.py
Labels: warmfix

#2318 [DEV-4531] Trim hashes to remove byte literal
  usaspending_api/references/v1/views.py
Labels: hotfix

#2312 Updated ES Mappings for Recipient Unique ID
  usaspending_api/common/query_with_filters.py
  usaspending_api/etl/es_award_template.json
  usaspending_api/etl/es_transaction_template.json
Labels: hotfix

#2321 Fix keyword total
  usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
  usaspending_api/search/v2/elasticsearch_helper.py
Labels: warmfix
