Repository fedspendingtransparency/usaspending-api, pull requests merged in 2020-03, with the labels that each got.

#2320 [DEV-3935] Prevent linking to agencies without agency pages
  usaspending_api/api_contracts/contracts/v2/awards/award_id.md
  usaspending_api/awards/tests/test_awards_v2.py
  usaspending_api/awards/v2/data_layer/orm.py
  usaspending_api/idvs/tests/test_awards_idv_v2.py
Labels: paired with website PR

#2324 [DEV-4446] Fix recipient locations on awards pages
  usaspending_api/awards/tests/test_awards_v2.py
  usaspending_api/awards/v2/data_layer/orm.py
  usaspending_api/awards/v2/data_layer/orm_mappers.py
Labels: paired with website PR

#2325 [DEV-3839] Contract/IDV Award page details tweak
  usaspending_api/api_contracts/contracts/v2/awards/award_id.md
  usaspending_api/awards/tests/test_awards_v2.py
  usaspending_api/awards/v2/data_layer/orm.py
Labels: paired with website PR

#2329 [DEV-4520] Correcting various issues with "Award Amount" Filter
  usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
  usaspending_api/awards/tests/test_sum_transaction_loans.py
  usaspending_api/awards/v2/filters/filter_helpers.py
  usaspending_api/awards/v2/filters/view_selector.py
  usaspending_api/awards/v2/lookups/matview_lookups.py
  usaspending_api/common/management/commands/matview_runner.py
  usaspending_api/common/query_with_filters.py
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
  usaspending_api/database_scripts/matview_generator/mv_award_summary.json
  usaspending_api/database_scripts/matview_generator/mv_contract_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_directpayment_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_grant_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_idv_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_loan_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_other_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_pre2008_award_search.json
  usaspending_api/database_scripts/matview_generator/subaward_view.json
  usaspending_api/database_scripts/matview_generator/summary_state_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_fed_acct_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_geo_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_month_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_recipient_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_view.json
  usaspending_api/database_scripts/matview_generator/summary_view.json
  usaspending_api/database_scripts/matview_generator/summary_view_cfda_number.json
  usaspending_api/database_scripts/matview_generator/summary_view_naics_codes.json
  usaspending_api/database_scripts/matview_generator/summary_view_psc_codes.json
  usaspending_api/database_scripts/matview_generator/universal_transaction_matview.json
  usaspending_api/database_scripts/matviews/functions_and_enums.sql
  usaspending_api/database_scripts/matviews/refresh_matviews.sql
  usaspending_api/database_scripts/matviews/vacuum_matviews.sql
  usaspending_api/etl/es_award_template.json
  usaspending_api/etl/es_etl_helpers.py
  usaspending_api/recipient/management/sql/restock_recipient_profile.sql
  usaspending_api/references/constants.py
  usaspending_api/search/models/base_award_search.py
  usaspending_api/search/models/mv_award_summary.py
  usaspending_api/search/models/subaward_view.py
  usaspending_api/search/models/summary_cfda_numbers_view.py
  usaspending_api/search/models/summary_naics_codes_view.py
  usaspending_api/search/models/summary_psc_codes_view.py
  usaspending_api/search/models/summary_state_view.py
  usaspending_api/search/models/summary_transaction_fed_acct_view.py
  usaspending_api/search/models/summary_transaction_geo_view.py
  usaspending_api/search/models/summary_transaction_month_view.py
  usaspending_api/search/models/summary_transaction_recipient_view.py
  usaspending_api/search/models/summary_transaction_view.py
  usaspending_api/search/models/summary_view.py
  usaspending_api/search/models/universal_transaction_matview.py
Labels: paired with website PR

#2330 [DEV-4430] Add new filter to split Prime and Sub Award types
  usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
  usaspending_api/awards/v2/filters/matview_filters.py
  usaspending_api/awards/v2/filters/sub_award.py
  usaspending_api/awards/v2/lookups/lookups.py
  usaspending_api/bulk_download/tests/test_download.py
  usaspending_api/download/filestreaming/download_generation.py
  usaspending_api/download/v2/base_download_viewset.py
  usaspending_api/download/v2/request_validations.py
  usaspending_api/download/v2/year_limited_downloads.py
Labels: paired with website PR

#2334 [DEV-4430] Split up the "Other" Award Type category for bulk award download
  usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
  usaspending_api/bulk_download/tests/test_download.py
  usaspending_api/download/v2/year_limited_downloads.py
Labels: paired with website PR

#2338 Update dependency versions
  requirements/requirements-app.txt
Labels: warmfix

#2341 [FIX/DEV-1671] Handling naive datetimes
  usaspending_api/common/helpers/date_helper.py
  usaspending_api/transactions/transaction_delete_journal_helpers.py
Labels: warmfix

#2348 [DEV-4430] Warmfix foreign country location selection on custom award download
  usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
  usaspending_api/bulk_download/tests/test_download.py
  usaspending_api/download/v2/request_validations.py
Labels: paired with website PR, warmfix

#2344 [DEV-4705] Fix Elasticsearch deletions
  usaspending_api/etl/es_etl_helpers.py
Labels: hotfix

#2343 [FIX] another overlooked edgecase
  usaspending_api/broker/helpers/delete_fabs_transactions.py
  usaspending_api/broker/management/commands/fabs_nightly_loader.py
  usaspending_api/transactions/agnostic_transaction_deletes.py
  usaspending_api/transactions/management/commands/delete_assistance_records.py
Labels: warmfix

#2358 [DEV-4693] Prevent ES caching
  usaspending_api/common/cache_decorator.py
Labels: hotfix

#2366 [DEV-4736] Use correct column for FPDS pop_country_name
  usaspending_api/bulk_download/tests/test_download.py
  usaspending_api/database_scripts/matview_generator/mv_contract_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_idv_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_pre2008_award_search.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_geo_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_month_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_view.json
  usaspending_api/database_scripts/matview_generator/universal_transaction_matview.json
  usaspending_api/search/tests/integration/test_spending_by_award_type.py
  usaspending_api/search/tests/integration/test_spending_over_time.py
  usaspending_api/search/tests/unit/test_spending_by_category.py
Labels: warmfix

#2377 WARMFIX: Minor update to NAICS logic
  usaspending_api/search/elasticsearch/filters/naics.py
Labels: warmfix
