Repository fedspendingtransparency/usaspending-api, pull requests merged in 2020-08, with the labels that each got.

#2690 QAT -> DEV
  usaspending_api/accounts/tests/unit/test_account_download_filter.py
  usaspending_api/accounts/v2/filters/account_download.py
  usaspending_api/awards/v2/filters/award_filters.py
  usaspending_api/awards/v2/filters/idv_filters.py
  usaspending_api/awards/v2/views/funding.py
  usaspending_api/common/helpers/fiscal_year_helpers.py
  usaspending_api/common/helpers/orm_helpers.py
  usaspending_api/common/query_with_filters.py
  usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
  usaspending_api/disaster/tests/conftest.py
  usaspending_api/disaster/tests/fixtures/award_count_data.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/fixtures/helpers.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/tests/integration/test_disaster_award_amount.py
  usaspending_api/disaster/tests/integration/test_federal_account_total.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/award/amount.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/disaster/v2/views/elasticsearch_base.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/download/download_utils.py
  usaspending_api/download/helpers/download_annotation_functions.py
  usaspending_api/download/lookups.py
  usaspending_api/download/tests/integration/test_download_disaster_recipient.py
  usaspending_api/download/v2/download_column_historical_lookups.py
  usaspending_api/download/v2/request_validations.py
  usaspending_api/etl/management/commands/load_multiple_submissions.py
  usaspending_api/etl/management/commands/load_submission.py
  usaspending_api/idvs/v2/views/funding.py
  usaspending_api/submissions/dabs_loader_queue_helpers.py
  usaspending_api/submissions/helpers.py
Labels: down merge

#2692 [DEV-5805] Tweak to submission id query for account downloads
  usaspending_api/submissions/helpers.py
Labels: warmfix

#2693 [DEV-5413] Minor tweak to one of the agency endpoints to prevent running query twice
  usaspending_api/disaster/v2/views/agency/spending.py
Labels: warmfix

#2694 Set DEFC reference data array order
  usaspending_api/references/v2/views/def_codes.py
Labels: warmfix

#2698 [DEV-5812] add publish date restriction
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
Labels: hotfix

#2697 [DEV-5822] Performance improvements
  usaspending_api/awards/models/financial_accounts_by_awards.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/award/amount.py
  usaspending_api/disaster/v2/views/award/count.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/disaster/v2/views/federal_account/federal_account_result.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/object_class/object_class_result.py
  usaspending_api/disaster/v2/views/object_class/spending.py
Labels: warmfix

#2702 [DEV-5822] Boost count and amount endpoint performance
  usaspending_api/awards/migrations/0073_auto_20200805_1511.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
  usaspending_api/common/helpers/orm_helpers.py
  usaspending_api/disaster/v2/urls.py
  usaspending_api/disaster/v2/views/award/amount.py
  usaspending_api/disaster/v2/views/award/count.py
  usaspending_api/disaster/v2/views/disaster_base.py
Labels: warmfix

#2699 Master -> QAT
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
Labels: down merge

#2703 [DEV-5825] Malformed json strings from Elasticsearch causing HTTP500s
  usaspending_api/disaster/v2/views/agency/loans.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/cfda/loans.py
  usaspending_api/disaster/v2/views/cfda/spending.py
  usaspending_api/disaster/v2/views/recipient/loans.py
  usaspending_api/disaster/v2/views/recipient/spending.py
  usaspending_api/disaster/v2/views/spending_by_geography.py
  usaspending_api/recipient/v2/views/recipients.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_agency_types.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_federal_account.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_industry_codes.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_recipient_duns.py
  usaspending_api/search/v2/views/spending_by_geography.py
Labels: warmfix

#2700 [DEV-5814] Logs download_count when downloading csv regardless of --skip-counts flag
  usaspending_api/etl/es_etl_helpers.py
  usaspending_api/etl/rapidloader.py
Labels: warmfix

#2709 [DEV-5825] Fixing issue introduced by first PR
  usaspending_api/common/elasticsearch/json_helpers.py
  usaspending_api/disaster/v2/views/agency/loans.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/cfda/loans.py
  usaspending_api/disaster/v2/views/cfda/spending.py
  usaspending_api/disaster/v2/views/recipient/loans.py
  usaspending_api/disaster/v2/views/recipient/spending.py
  usaspending_api/disaster/v2/views/spending_by_geography.py
  usaspending_api/recipient/v2/views/recipients.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_agency_types.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_federal_account.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_industry_codes.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_recipient_duns.py
  usaspending_api/search/v2/views/spending_by_geography.py
Labels: warmfix

#2701 [DEV-5806] Ignore the 500k limit for Disaster Recipient Download
  usaspending_api/download/filestreaming/download_generation.py
  usaspending_api/download/helpers/disaster_filter_functions.py
  usaspending_api/download/helpers/download_annotation_functions.py
  usaspending_api/download/lookups.py
  usaspending_api/download/tests/unit/test_sql_annotations.py
  usaspending_api/download/v2/download_column_historical_lookups.py
  usaspending_api/download/v2/request_validations.py
  usaspending_api/search/models/vw_award_search.py
Labels: warmfix

#2708 Mod/dev 5789 add definitions
  usaspending_api/data/USAspendingGlossary.xlsx
Labels: warmfix

#2704 QAT -> DEV
  usaspending_api/awards/migrations/0073_auto_20200805_1511.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
  usaspending_api/common/elasticsearch/json_helpers.py
  usaspending_api/common/helpers/orm_helpers.py
  usaspending_api/data/USAspendingGlossary.xlsx
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/v2/urls.py
  usaspending_api/disaster/v2/views/agency/loans.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/award/amount.py
  usaspending_api/disaster/v2/views/award/count.py
  usaspending_api/disaster/v2/views/cfda/loans.py
  usaspending_api/disaster/v2/views/cfda/spending.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/disaster/v2/views/federal_account/federal_account_result.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/object_class/object_class_result.py
  usaspending_api/disaster/v2/views/object_class/spending.py
  usaspending_api/disaster/v2/views/recipient/count.py
  usaspending_api/disaster/v2/views/recipient/loans.py
  usaspending_api/disaster/v2/views/recipient/spending.py
  usaspending_api/disaster/v2/views/spending_by_geography.py
  usaspending_api/download/filestreaming/download_generation.py
  usaspending_api/download/helpers/disaster_filter_functions.py
  usaspending_api/download/helpers/download_annotation_functions.py
  usaspending_api/download/lookups.py
  usaspending_api/download/tests/unit/test_sql_annotations.py
  usaspending_api/download/v2/download_column_historical_lookups.py
  usaspending_api/download/v2/request_validations.py
  usaspending_api/etl/es_etl_helpers.py
  usaspending_api/etl/rapidloader.py
  usaspending_api/recipient/v2/views/recipients.py
  usaspending_api/references/v2/views/def_codes.py
  usaspending_api/search/models/vw_award_search.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_agency_types.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_federal_account.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_industry_codes.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_recipient_duns.py
  usaspending_api/search/v2/views/spending_by_geography.py
  usaspending_api/submissions/helpers.py
Labels: down merge

#2714 QAT -> DEV downmerge
  usaspending_api/data/USAspendingGlossary.xlsx
Labels: down merge

#2725 QAT -> DEV
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
  usaspending_api/database_scripts/matview_generator/mv_contract_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_directpayment_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_grant_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_idv_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_loan_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_other_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_pre2008_award_search.json
  usaspending_api/database_scripts/matview_generator/universal_transaction_matview.json
  usaspending_api/search/models/base_award_search.py
  usaspending_api/search/models/universal_transaction_matview.py
Labels: down merge

#2728 [DEV-5855] Remove the timestamp truncation from ES ETL
  usaspending_api/etl/es_etl_helpers.py
  usaspending_api/etl/management/commands/es_rapidloader.py
  usaspending_api/etl/tests/test_es_rapidloader.py
Labels: hotfix

#2729 Master -> QAT
  usaspending_api/etl/es_etl_helpers.py
  usaspending_api/etl/management/commands/es_rapidloader.py
  usaspending_api/etl/tests/test_es_rapidloader.py
Labels: down merge

#2727 [DEV-5842] Create new matview for COVID Financial Accounts
  usaspending_api/api_contracts/contracts/v2/disaster/agency/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/award/amount.md
  usaspending_api/api_contracts/contracts/v2/disaster/recipient/count.md
  usaspending_api/awards/migrations/0001_initial.py
  usaspending_api/awards/models/__init__.py
  usaspending_api/awards/models/mv_covid_financial_account.py
  usaspending_api/common/matview_manager.py
  usaspending_api/database_scripts/matview_generator/mv_covid_financial_account.json
  usaspending_api/disaster/tests/fixtures/agency_count_data.py
  usaspending_api/disaster/tests/fixtures/award_count_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/fixtures/recipient_count_data.py
  usaspending_api/disaster/tests/integration/test_disaster_award_amount.py
  usaspending_api/disaster/v2/views/agency/count.py
  usaspending_api/disaster/v2/views/award/amount.py
  usaspending_api/disaster/v2/views/recipient/count.py
Labels: warmfix

#2723 [DEV-5855] Efficiency Improvements to Elasticsearch ETL
  usaspending_api/etl/es_etl_helpers.py
  usaspending_api/etl/management/commands/es_configure.py
  usaspending_api/etl/management/commands/es_rapidloader.py
  usaspending_api/etl/rapidloader.py
  usaspending_api/etl/tests/test_es_rapidloader.py
  usaspending_api/settings.py
Labels: warmfix

#2743 adding headers as tags to root span in datadog trace
  usaspending_api/common/datadog.py
  usaspending_api/settings.py
Labels: ready for review

#2746 [DEV-5322] change documentation in QAT, not just DEV
  usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
Labels: warmfix

#2752 [DEV-5880] Fixing over-counted outlays (PR #2 for QAT testing)
  usaspending_api/awards/tests/test_awards_v2.py
  usaspending_api/awards/v2/data_layer/sql.py
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/database_scripts/matview_generator/mv_covid_financial_account.json
  usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_b.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
  usaspending_api/disaster/tests/conftest.py
  usaspending_api/disaster/tests/fixtures/award_count_data.py
  usaspending_api/disaster/tests/fixtures/cfda_data.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/fixtures/overview_data.py
  usaspending_api/disaster/tests/fixtures/recipient_location_data.py
  usaspending_api/disaster/tests/integration/test_overview.py
  usaspending_api/disaster/v2/views/disaster_base.py
Labels: warmfix

#2747 [DEV-5880] Utilizing New is_final_balances_for_fy Column
  usaspending_api/awards/tests/test_awards_v2.py
  usaspending_api/awards/v2/data_layer/sql.py
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/database_scripts/matview_generator/mv_covid_financial_account.json
  usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_b.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
  usaspending_api/disaster/tests/conftest.py
  usaspending_api/disaster/tests/fixtures/award_count_data.py
  usaspending_api/disaster/tests/fixtures/cfda_data.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/fixtures/overview_data.py
  usaspending_api/disaster/tests/fixtures/recipient_location_data.py
  usaspending_api/disaster/tests/integration/test_overview.py
  usaspending_api/disaster/v2/views/disaster_base.py
Labels: do not merge

#2745 [DEV-5880] Efficient mechanism to determine latest submission per agency in a given FY
  usaspending_api/awards/tests/test_awards_v2.py
  usaspending_api/awards/v2/data_layer/sql.py
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/database_scripts/matview_generator/mv_covid_financial_account.json
  usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_b.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
  usaspending_api/disaster/tests/conftest.py
  usaspending_api/disaster/tests/fixtures/award_count_data.py
  usaspending_api/disaster/tests/fixtures/cfda_data.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/fixtures/overview_data.py
  usaspending_api/disaster/tests/fixtures/recipient_location_data.py
  usaspending_api/disaster/tests/integration/test_overview.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/etl/management/commands/populate_is_final_balances_for_fy.py
  usaspending_api/etl/tests/integration/test_load_multiple_submissions.py
  usaspending_api/etl/tests/integration/test_populate_is_final_balances_for_fy.py
  usaspending_api/submissions/migrations/0012_submissionattributes_is_final_balances_for_fy.py
  usaspending_api/submissions/models/submission_attributes.py
Labels: hotfix

#2754 [DEV-5943] Leveraging proper concat usage in postgres requires non-django function
  usaspending_api/accounts/v2/filters/account_download.py
  usaspending_api/disaster/v2/views/object_class/loans.py
  usaspending_api/download/helpers/download_annotation_functions.py
Labels: warmfix
