Repository fedspendingtransparency/usaspending-api, pull requests merged in 2020-01, with the labels that each got.

#2195 Mod/warmfix 4116 download refactor
  usaspending_api/download/filestreaming/download_generation.py
  usaspending_api/download/helpers/download_annotation_functions.py
  usaspending_api/download/management/commands/populate_monthly_delta_files.py
  usaspending_api/download/tests/unit/test_file_generation.py
  usaspending_api/download/tests/unit/test_sql_annotations.py
Labels: WARMFIX

#2211 [DEV-4121] Change download endpoint response
  usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
  usaspending_api/api_contracts/contracts/v2/bulk_download/status.md
  usaspending_api/api_contracts/contracts/v2/download/accounts.md
  usaspending_api/api_contracts/contracts/v2/download/assistance.md
  usaspending_api/api_contracts/contracts/v2/download/awards.md
  usaspending_api/api_contracts/contracts/v2/download/contract.md
  usaspending_api/api_contracts/contracts/v2/download/idv.md
  usaspending_api/api_contracts/contracts/v2/download/status.md
  usaspending_api/api_contracts/contracts/v2/download/transactions.md
  usaspending_api/bulk_download/tests/test_download.py
  usaspending_api/download/tests/integration/test_download_accounts.py
  usaspending_api/download/tests/integration/test_download_accounts_dev_3997.py
  usaspending_api/download/tests/integration/test_download_assistance.py
  usaspending_api/download/tests/integration/test_download_awards.py
  usaspending_api/download/tests/integration/test_download_contract.py
  usaspending_api/download/tests/integration/test_download_idv.py
  usaspending_api/download/tests/integration/test_download_transactions.py
  usaspending_api/download/v2/base_download_viewset.py
  usaspending_api/download/v2/download_status.py
Labels: paired with website PR

#2227 [DEV-4109] Part 2.1: Fixing FABS award updates
  usaspending_api/etl/award_helpers.py
Labels: WARMFIX

#2219 [DEV-4109] Part 3: Update Scripts
  usaspending_api/common/operations_reporter.py
  usaspending_api/database_scripts/job_archive/management/commands/dev_4109_repair_awards.py
  usaspending_api/database_scripts/job_archive/recompute_all_awards.py
  usaspending_api/settings.py
Labels: WARMFIX

#2234 Less fragile delete statements for views
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
  usaspending_api/database_scripts/matviews/vw_award_search.sql
Labels: WARMFIX

#2233 [DEV-4109] Part 3.1: Follow-up tweaks to script after test runs
  usaspending_api/database_scripts/job_archive/recompute_all_awards.py
  usaspending_api/etl/award_helpers.py
Labels: WARMFIX

#2247 [OPS-995,OPS-1034] Datadog APM config cleanup and tracing of bulk downloads
  config/uwsgi.ini
  requirements/requirements-app.txt
  usaspending_api/download/management/commands/download_sqs_worker.py
  usaspending_api/settings.py
Labels: dependencies

#2251 [DEV-4098] Fix download header name
  usaspending_api/download/v2/download_column_historical_lookups.py
Labels: warmfix

#2254 [DEV-3074] Add migrations for on_delete changes
  usaspending_api/awards/migrations/0001_initial.py
Labels: warmfix
