Repository fedspendingtransparency/usaspending-api, pull requests merged in 2020-05, with the labels that each got.

#2453 [DEV-4836] Corrected update_date values in SQL view
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
Labels: warmfix

#2454 QAT -> DEV
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
  usaspending_api/search/v2/es_sanitization.py
Labels: down merge

#2466 [DEV-4879] Data quality around country code and name
  usaspending_api/awards/tests/unit/test_location_filter_geocode.py
  usaspending_api/bulk_download/tests/test_download.py
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
  usaspending_api/database_scripts/matview_generator/mv_contract_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_directpayment_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_grant_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_idv_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_loan_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_other_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_pre2008_award_search.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_geo_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_month_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_view.json
  usaspending_api/database_scripts/matview_generator/universal_transaction_matview.json
  usaspending_api/references/tests/integration/test_city.py
  usaspending_api/search/tests/data/spending_by_award_test_data.py
  usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
  usaspending_api/search/tests/integration/test_spending_by_award_type.py
  usaspending_api/search/tests/integration/test_spending_by_geography_city.py
  usaspending_api/search/tests/integration/test_spending_over_time.py
  usaspending_api/search/tests/unit/test_tas_search.py
  usaspending_api/tests/test_award_index_elasticsearch.py
Labels: warmfix

#2473 [FIX] Reduce max number of uwsgi workers
  config/uwsgi.ini
Labels: hotfix

#2475 Master -> QAT
  config/uwsgi.ini
Labels: down merge

#2476 QAT -> DEV
  config/uwsgi.ini
  usaspending_api/awards/tests/unit/test_location_filter_geocode.py
  usaspending_api/bulk_download/tests/test_download.py
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
  usaspending_api/database_scripts/matview_generator/mv_contract_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_directpayment_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_grant_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_idv_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_loan_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_other_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_pre2008_award_search.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_geo_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_month_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_view.json
  usaspending_api/database_scripts/matview_generator/universal_transaction_matview.json
  usaspending_api/references/tests/integration/test_city.py
  usaspending_api/search/tests/data/spending_by_award_test_data.py
  usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
  usaspending_api/search/tests/integration/test_spending_by_award_type.py
  usaspending_api/search/tests/integration/test_spending_by_geography_city.py
  usaspending_api/search/tests/integration/test_spending_over_time.py
  usaspending_api/search/tests/unit/test_tas_search.py
  usaspending_api/tests/test_award_index_elasticsearch.py
Labels: down merge

#2477 [FIX] enabling memory-report for cheaper memory limits
  config/uwsgi.ini
Labels: warmfix

#2479 [FIX] added config line to support uwsgi memory limits
  config/uwsgi.ini
Labels: hotfix

#2480 QAT -> DEV
  config/uwsgi.ini
Labels: down merge

#2486 Set Elasticsearch Downloads Shard Size
  usaspending_api/download/helpers/elasticsearch_download_functions.py
  usaspending_api/search/v2/elasticsearch_helper.py
Labels: warmfix

#2488 Reconfigure uwsgi.ini for a smaller server node
  config/uwsgi.ini
Labels: warmfix

#2489 QAT -> DEV
  config/uwsgi.ini
Labels: down merge

#2491 [HOTFIX] Keyword search field update
  usaspending_api/common/query_with_filters.py
Labels: hotfix

#2492 [WARMFIX] Fix agency codes
  usaspending_api/search/v2/views/spending_by_award.py
Labels: warmfix

#2494 Master -> QAT
  usaspending_api/common/query_with_filters.py
Labels: down merge

#2501 Warmfix/update rosetta loader
  usaspending_api/references/management/commands/load_rosetta.py
  usaspending_api/references/tests/data/20181219rosetta-test-file.xlsx
  usaspending_api/references/tests/integration/test_load_rosetta.py
Labels: paired with website PR, warmfix

#2503 Qat -> Dev downmerge
  usaspending_api/references/management/commands/load_rosetta.py
  usaspending_api/references/tests/data/20181219rosetta-test-file.xlsx
  usaspending_api/references/tests/integration/test_load_rosetta.py
Labels: down merge
