Repository fedspendingtransparency/usaspending-api, pull requests merged in 2020-06, with the labels that each got.

#2507 [DEV-5252] Fix sanitization
  usaspending_api/common/query_with_filters.py
Labels: warmfix

#2513 [DEV-5323/5324] FABS delete bugs warmfix
  usaspending_api/broker/helpers/delete_fabs_transactions.py
  usaspending_api/broker/helpers/delete_stale_fabs.py
  usaspending_api/broker/management/commands/fabs_nightly_loader.py
  usaspending_api/broker/tests/integration/test_delete_fabs.py
  usaspending_api/broker/tests/integration/test_get_delete_pks_for_afa_keys.py
  usaspending_api/transactions/agnostic_transaction_deletes.py
  usaspending_api/transactions/management/commands/delete_assistance_records.py
  usaspending_api/transactions/management/commands/transfer_assistance_records.py
Labels: warmfix

#2524 [FIX] Update Conditional in transaction load script
  usaspending_api/transactions/agnostic_transaction_loader.py
Labels: warmfix

#2525 QAT -> DEV
  usaspending_api/transactions/agnostic_transaction_loader.py
Labels: down merge

#2527 Update es_sanitization.py
  usaspending_api/common/query_with_filters.py
  usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
  usaspending_api/search/tests/unit/test_es_sanitize.py
  usaspending_api/search/v2/es_sanitization.py
Labels: warmfix

#2528 QAT -> DEV
  usaspending_api/common/query_with_filters.py
  usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
  usaspending_api/search/tests/unit/test_es_sanitize.py
  usaspending_api/search/v2/es_sanitization.py
Labels: down merge

#2531 [DEV-5041] Fix minor logging issue
  usaspending_api/etl/management/commands/load_multiple_submissions.py
Labels: warmfix

#2534 [DEV-5398] Removing Two Materialized Views
  usaspending_api/common/matview_manager.py
  usaspending_api/database_scripts/matview_generator/summary_transaction_month_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_view.json
  usaspending_api/database_scripts/matviews/drop_old_matviews.sql
  usaspending_api/database_scripts/matviews/refresh_matviews.sql
  usaspending_api/database_scripts/matviews/vacuum_matviews.sql
  usaspending_api/search/migrations/0001_initial.py
  usaspending_api/search/models/__init__.py
  usaspending_api/search/models/summary_transaction_month_view.py
  usaspending_api/search/models/summary_transaction_view.py
Labels: warmfix

#2536 QAT -> DEV
  usaspending_api/common/matview_manager.py
  usaspending_api/database_scripts/matview_generator/summary_transaction_month_view.json
  usaspending_api/database_scripts/matview_generator/summary_transaction_view.json
  usaspending_api/database_scripts/matviews/drop_old_matviews.sql
  usaspending_api/database_scripts/matviews/refresh_matviews.sql
  usaspending_api/database_scripts/matviews/vacuum_matviews.sql
  usaspending_api/search/migrations/0001_initial.py
  usaspending_api/search/models/__init__.py
  usaspending_api/search/models/summary_transaction_month_view.py
  usaspending_api/search/models/summary_transaction_view.py
Labels: down merge

#2558 updating datadog trace client
  requirements/requirements-app.txt
Labels: ready for review
