Repository fedspendingtransparency/usaspending-api, pull requests merged in 2020-09, with the labels that each got.

#2758 [DEV-6033] Regex to handle quotes in a json formatted string
  usaspending_api/common/elasticsearch/json_helpers.py
Labels: hotfix

#2760 Downmerge Master -> QAT
  usaspending_api/common/elasticsearch/json_helpers.py
Labels: down merge

#2753 QAT -> DEV
  usaspending_api/accounts/v2/filters/account_download.py
  usaspending_api/awards/tests/test_awards_v2.py
  usaspending_api/awards/v2/data_layer/sql.py
  usaspending_api/common/elasticsearch/json_helpers.py
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/database_scripts/matview_generator/mv_covid_financial_account.json
  usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_b.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
  usaspending_api/disaster/tests/conftest.py
  usaspending_api/disaster/tests/fixtures/award_count_data.py
  usaspending_api/disaster/tests/fixtures/cfda_data.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/fixtures/overview_data.py
  usaspending_api/disaster/tests/fixtures/recipient_location_data.py
  usaspending_api/disaster/tests/integration/test_overview.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/disaster/v2/views/object_class/loans.py
  usaspending_api/download/helpers/download_annotation_functions.py
Labels: down merge

#2756 [DEV-5943] new distinct award field in FinancialAccountsByAwards
  usaspending_api/awards/migrations/0074_financialaccountsbyawards_distinct_award_key.py
  usaspending_api/awards/migrations/0075_financialaccountsbyawards_distinct_award_key.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
  usaspending_api/database_scripts/job_archive/backfill_faba_distinct_award_key.py
  usaspending_api/disaster/tests/fixtures/award_count_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/v2/views/award/amount.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/etl/submission_loader_helpers/file_c.py
Labels: warmfix

#2755 [DEV-5939] Remove agency links
  usaspending_api/api_contracts/contracts/v2/spending.md
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/spending_explorer/v2/filters/explorer.py
  usaspending_api/spending_explorer/v2/filters/type_filter.py
Labels: paired with website PR

#2773 [DEV-6035] Use inner join for agency count
  usaspending_api/disaster/v2/views/agency/count.py
Labels: warmfix

#2782 Update dredd version so Travis-CI builds can complete
  .travis.yml
Labels: warmfix

#2781 [OPS-1470] Refactored summary_award_recipient ETL script to incrementally update table
  usaspending_api/recipient/management/sql/restock_summary_award_recipient.sql
Labels: warmfix

#2783 QAT -> DEV
  .travis.yml
  usaspending_api/recipient/management/sql/restock_summary_award_recipient.sql
Labels: down merge

#2780 [DEV-5944] Adding partial index to support index-only query for disaster award endpoint
  usaspending_api/awards/migrations/0076_auto_20200916_0312.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
Labels: warmfix

#2785 [DEV-5252] Elasticsearch sanitization fix
  usaspending_api/references/tests/integration/test_city.py
  usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
  usaspending_api/search/v2/es_sanitization.py
Labels: warmfix

#2786 [DEV-5944] Adding piid to partial index for disaster awards endpoint
  usaspending_api/awards/migrations/0077_auto_20200917_2223.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
Labels: warmfix

#2784 [DEV-6125] Refactored recipient_profile ETL script to incrementally update table
  usaspending_api/recipient/management/sql/restock_recipient_profile.sql
Labels: warmfix

#2792 Downmerge QAT -> DEV
  usaspending_api/awards/migrations/0076_auto_20200916_0312.py
  usaspending_api/awards/migrations/0077_auto_20200917_2223.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
  usaspending_api/recipient/management/sql/restock_recipient_profile.sql
  usaspending_api/references/tests/integration/test_city.py
  usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
  usaspending_api/search/v2/es_sanitization.py
Labels: down merge

#2800 [DEV-6179] Fix 'all' agency case breaking downloads
  usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
  usaspending_api/api_contracts/contracts/v2/download/awards.md
  usaspending_api/api_contracts/contracts/v2/download/transactions.md
  usaspending_api/download/v2/request_validations.py
  usaspending_api/download/v2/year_limited_downloads.py
Labels: hotfix

#2802 Master -> QAT
  usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
  usaspending_api/api_contracts/contracts/v2/download/awards.md
  usaspending_api/api_contracts/contracts/v2/download/transactions.md
  usaspending_api/download/v2/request_validations.py
  usaspending_api/download/v2/year_limited_downloads.py
Labels: down merge

#2803 QAT -> DEV
  usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
  usaspending_api/api_contracts/contracts/v2/download/awards.md
  usaspending_api/api_contracts/contracts/v2/download/transactions.md
  usaspending_api/download/v2/request_validations.py
  usaspending_api/download/v2/year_limited_downloads.py
Labels: down merge

#2804 HOTFIX: [DEV-6181] Delete ES docs before incrementally UPSERTing to avoid dupes
  usaspending_api/etl/es_etl_helpers.py
  usaspending_api/etl/management/commands/es_rapidloader.py
  usaspending_api/etl/rapidloader.py
Labels: hotfix, ready for review

#2810 [DEV-6181] Downmerging hotfix PR 2804 from master down to qat and resolving merge conflicts
  usaspending_api/etl/elasticsearch_loader_helpers/es_etl_helpers.py
  usaspending_api/etl/elasticsearch_loader_helpers/rapidloader.py
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
  usaspending_api/recipient/tests/integration/test_state.py
Labels: down merge

#2816 [DEV-6181] Downmerging hotfix PR 2804 from qat down to dev and resolving merge conflicts
  usaspending_api/etl/elasticsearch_loader_helpers/__init__.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/load_data.py
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
  usaspending_api/recipient/tests/integration/test_state.py
Labels: down merge
