Repository fedspendingtransparency/usaspending-api, pull requests merged in 2020-04, with the labels that each got.

#2381 WARMFIX: dev-4782 reject odd length naics codes
  usaspending_api/awards/v2/filters/matview_filters.py
  usaspending_api/search/elasticsearch/filters/naics.py
  usaspending_api/search/tests/integration/test_spending_over_time.py
  usaspending_api/search/tests/unit/filters/naics.py
Labels: warmfix

#2400 [DEV-4768] district per capita
  usaspending_api/search/v2/views/spending_by_geography.py
Labels: warmfix

#2405 [DEV-4506] Obtain recipient_id when record doesn't contain DUNS
  usaspending_api/common/recipient_lookups.py
Labels: warmfix

#2407 Merge recipient hash lookup back into DEV from QAT
  usaspending_api/common/recipient_lookups.py
Labels: down merge

#2412 [FIX] Monthly file generation script outdated
  usaspending_api/download/management/commands/populate_monthly_files.py
Labels: warmfix

#2413 Qat -> Dev
  usaspending_api/download/management/commands/populate_monthly_files.py
Labels: warmfix

#2423 [DEV-4873] Add extra logging to FPDS deletes
  usaspending_api/common/helpers/s3_helpers.py
  usaspending_api/transactions/transaction_delete_journal_helpers.py
Labels: hotfix

#2425 [DEV-4873] Fix S3 file datetime filtering for FPDS loader
  usaspending_api/transactions/transaction_delete_journal_helpers.py
Labels: hotfix

#2426 Master -> QAT
  usaspending_api/common/helpers/s3_helpers.py
  usaspending_api/transactions/transaction_delete_journal_helpers.py
Labels: down merge

#2436 WARMFIX [DEV-4963] Sanitize elasticsearch text input
  usaspending_api/common/query_with_filters.py
  usaspending_api/references/v2/views/city.py
  usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
  usaspending_api/search/tests/unit/test_es_sanitize.py
  usaspending_api/search/v2/elasticsearch_helper.py
  usaspending_api/search/v2/es_sanitization.py
  usaspending_api/search/v2/views/search_elasticsearch.py
Labels: warmfix

#2438 [DEV-4818] Fix sorting by Mod column on Keyword Search
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/search/tests/integration/test_spending_by_transaction.py
Labels: warmfix

#2439 Downmerge QAT -> DEV
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/common/query_with_filters.py
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/references/v2/views/city.py
  usaspending_api/search/tests/integration/test_spending_by_transaction.py
  usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
  usaspending_api/search/tests/unit/test_es_sanitize.py
  usaspending_api/search/v2/elasticsearch_helper.py
  usaspending_api/search/v2/es_sanitization.py
  usaspending_api/search/v2/views/search_elasticsearch.py
Labels: down merge

#2446 WARMFIX [DEV-4819] Fix sanitization regex
  usaspending_api/search/v2/es_sanitization.py
Labels: warmfix
