Repository fedspendingtransparency/usaspending-api, pull requests merged in 2020-07, with the labels that each got.

#2563 [DEV-5170] Warmfix Django grouping issue
  usaspending_api/spending_explorer/v2/filters/type_filter.py
Labels: warmfix

#2566 [DEV-5170] Warmfix Django grouping issue attempt 2
  usaspending_api/spending_explorer/v2/filters/type_filter.py
Labels: warmfix

#2564 QAT => DEV warmfix downmerge
  usaspending_api/spending_explorer/v2/filters/type_filter.py
Labels: down merge

#2557 Creating `mv_award_search` to prototype ETL and API queries
  usaspending_api/common/matview_manager.py
  usaspending_api/database_scripts/matview_generator/mv_award_search.json
  usaspending_api/database_scripts/matviews/drop_old_matviews.sql
  usaspending_api/database_scripts/matviews/refresh_matviews.sql
  usaspending_api/database_scripts/matviews/vacuum_matviews.sql
  usaspending_api/search/migrations/0001_initial.py
  usaspending_api/search/models/__init__.py
  usaspending_api/search/models/mv_award_search.py
Labels: do not merge

#2580 [DEV-5121] Synchronize FABS/FPDS transactions
  usaspending_api/broker/management/commands/fabs_nightly_loader.py
  usaspending_api/common/helpers/sql_helpers.py
  usaspending_api/database_scripts/job_archive/management/commands/resynchronize_fabs_and_fpds.py
  usaspending_api/etl/transaction_loaders/fpds_loader.py
  usaspending_api/transactions/agnostic_transaction_deletes.py
  usaspending_api/transactions/management/commands/delete_assistance_records.py
  usaspending_api/transactions/management/commands/delete_procurement_records.py
Labels: warmfix

#2578 [DEV-5487] Add columns to federal account endpoint
  usaspending_api/api_contracts/contracts/v2/awards/funding.md
  usaspending_api/awards/v2/views/funding.py
Labels: paired with website PR

#2583 DOWNMERGE QAT => DEV for FABS/FPDS re-synchronization script
  usaspending_api/broker/management/commands/fabs_nightly_loader.py
  usaspending_api/common/helpers/sql_helpers.py
  usaspending_api/database_scripts/job_archive/management/commands/resynchronize_fabs_and_fpds.py
  usaspending_api/etl/transaction_loaders/fpds_loader.py
  usaspending_api/transactions/agnostic_transaction_deletes.py
  usaspending_api/transactions/management/commands/delete_assistance_records.py
  usaspending_api/transactions/management/commands/delete_procurement_records.py
Labels: down merge

#2606 [DEV-5302] Replacing exception with logging
  usaspending_api/disaster/management/commands/generate_covid19_download.py
Labels: warmfix

#2605 [DEV-5299] Only allow assistance filters and minor cleanup on API contract
  usaspending_api/api_contracts/contracts/v2/disaster/agency/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/agency/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/recipient/loans.md
  usaspending_api/disaster/tests/integration/test_cfda_count.py
  usaspending_api/disaster/tests/integration/test_cfda_spending.py
  usaspending_api/disaster/v2/views/cfda/count.py
  usaspending_api/disaster/v2/views/cfda/spending.py
  usaspending_api/disaster/v2/views/disaster_base.py
Labels: warmfix

#2608 QAT -> DEV
  usaspending_api/api_contracts/contracts/v2/disaster/agency/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/agency/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/recipient/loans.md
  usaspending_api/disaster/management/commands/generate_covid19_download.py
  usaspending_api/disaster/tests/integration/test_cfda_count.py
  usaspending_api/disaster/tests/integration/test_cfda_spending.py
  usaspending_api/disaster/v2/views/cfda/count.py
  usaspending_api/disaster/v2/views/cfda/spending.py
  usaspending_api/disaster/v2/views/disaster_base.py
Labels: down merge

#2633 [UNTICKETED] Band-Aid (tm) for caching issue
  usaspending_api/common/cache_decorator.py
Labels: warmfix

#2640 [DEV-5717] Ensure Account Data is only displayed after the DABS due date
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/disaster/tests/fixtures/cfda_data.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_loans.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/search/tests/data/spending_by_award_test_data.py
Labels: warmfix

#2641 [WARMFIX] QAT -> Staging to sync warmfix #2640
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/disaster/tests/fixtures/cfda_data.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_loans.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/search/tests/data/spending_by_award_test_data.py
Labels: warmfix

#2667 [DEV-5771] update download SQL (QAT)
  usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
Labels: warmfix

#2669 [DEV-5602] Minor fix to the query text filter for ES (QAT)
  usaspending_api/common/query_with_filters.py
Labels: warmfix

#2673 [DEV-5696] Add failure reprocessing to submision loader (Q.A.T.)
  usaspending_api/etl/management/commands/load_multiple_submissions.py
  usaspending_api/etl/management/commands/load_submission.py
  usaspending_api/submissions/dabs_loader_queue_helpers.py
Labels: warmfix

#2674 [DEV-5696] Add failure reprocessing to submision loader (STAGING)
  usaspending_api/etl/management/commands/load_multiple_submissions.py
  usaspending_api/etl/management/commands/load_submission.py
  usaspending_api/submissions/dabs_loader_queue_helpers.py
Labels: warmfix

#2677 [DEV-5557] Point to the right download for COVID Page Download (QAT)
  usaspending_api/download/download_utils.py
  usaspending_api/download/lookups.py
  usaspending_api/download/tests/integration/test_download_disaster_recipient.py
Labels: warmfix

#2679 [DEV-5557] Handle nonzero case for downloads (QAT)
  usaspending_api/common/query_with_filters.py
  usaspending_api/disaster/v2/views/elasticsearch_base.py
  usaspending_api/download/v2/request_validations.py
Labels: warmfix

#2682 added values to award amounts
  usaspending_api/disaster/v2/views/award/amount.py
Labels: warmfix

#2684 [DEV-5696] Reduce submission loader false negatives (QAT)
  usaspending_api/etl/management/commands/load_multiple_submissions.py
  usaspending_api/etl/management/commands/load_submission.py
  usaspending_api/submissions/dabs_loader_queue_helpers.py
Labels: warmfix

#2681 [DEV-5560] Fix custom account download (QAT)
  usaspending_api/accounts/tests/unit/test_account_download_filter.py
  usaspending_api/accounts/v2/filters/account_download.py
  usaspending_api/awards/v2/filters/award_filters.py
  usaspending_api/awards/v2/filters/idv_filters.py
  usaspending_api/common/helpers/fiscal_year_helpers.py
  usaspending_api/common/helpers/orm_helpers.py
  usaspending_api/disaster/tests/fixtures/helpers.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/download/v2/download_column_historical_lookups.py
  usaspending_api/download/v2/request_validations.py
  usaspending_api/submissions/helpers.py
Labels: warmfix
