Repository fedspendingtransparency/usaspending-api, pull requests merged in 2021-04, with the labels that each got.

#3039 [DEV-6756] Check es doc duplication management command
  usaspending_api/etl/management/commands/check_es_doc_duplication.py
Labels: ready for review

#3098 [DEV-7116] Adds Date Parsing to dabs_submission_window_schedule Class
  usaspending_api/submissions/management/commands/load_dabs_submission_window_schedule.py
  usaspending_api/submissions/models/dabs_submission_window_schedule.py
Labels: warmfix

#3101 Downmerge QAT -> Dev
  usaspending_api/submissions/management/commands/load_dabs_submission_window_schedule.py
  usaspending_api/submissions/models/dabs_submission_window_schedule.py
Labels: down merge

#3112 [DEV-7191] Return None instead of 0.0 when null
  usaspending_api/reporting/tests/integration/test_agencies_publish_dates.py
  usaspending_api/reporting/v2/views/agencies/publish_dates.py
Labels: warmfix
