Repository fedspendingtransparency/usaspending-api, pull requests merged in 2021-05, with the labels that each got.

#3116 [DEV-7191] Fix sorting for non FY 2021 table views when sorting Fiscal Period
  usaspending_api/reporting/v2/views/agencies/publish_dates.py
Labels: warmfix

#3119 Downmerge QAT -> Dev
  usaspending_api/reporting/tests/integration/test_agencies_publish_dates.py
  usaspending_api/reporting/tests/integration/test_agency_code_overview.py
  usaspending_api/reporting/v2/views/agencies/overview.py
  usaspending_api/reporting/v2/views/agencies/publish_dates.py
  usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py
Labels: down merge

#3126 [DEV-7281] Correct calculation of percent TBR on reporting/toptier/overview endpoint
  usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py
Labels: warmfix

#3135 [DEV-7362] Pull over correct toptier_flag and user_selectable for all agencies
  usaspending_api/references/management/commands/load_agencies_sql/agency_query.sql
Labels: hotfix

#3136 Downmerge Master -> Staging
  usaspending_api/references/management/commands/load_agencies_sql/agency_query.sql
Labels: down merge

#3137 Downmerge Staging -> QAT
  usaspending_api/references/management/commands/load_agencies_sql/agency_query.sql
Labels: down merge

#3138 Downmerge QAT -> Dev
  usaspending_api/references/management/commands/load_agencies_sql/agency_query.sql
Labels: down merge

#3139 [DEV-7156] Adds use-cache query param to submission_periods endpoint
  usaspending_api/api_contracts/contracts/v2/references/submission_periods.md
  usaspending_api/references/v2/views/submission_periods.py
Labels: hotfix

#3141 [DEV-7388] fix covid sorting
  usaspending_api/search/v2/views/spending_by_award.py
Labels: warmfix

#3148 Downmerge Staging -> QAT
  usaspending_api/search/v2/views/spending_by_award.py
Labels: down merge
