Repository fedspendingtransparency/usaspending-api, pull requests merged in 2021-01, with the labels that each got.

#2901 Fix Broken Tests in Travis
  usaspending_api/agency/tests/integration/test_agency_budget_function.py
  usaspending_api/agency/tests/integration/test_agency_federal_account_list.py
  usaspending_api/agency/tests/integration/test_agency_object_class_list.py
  usaspending_api/agency/tests/integration/test_agency_program_activity_list.py
  usaspending_api/common/helpers/fiscal_year_helpers.py
  usaspending_api/reporting/tests/integration/test_agencies_overview.py
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_tas.py
  usaspending_api/settings.py
Labels: warmfix

#2907 [Hotfix][DEV-6413] Account for COVID FY with total budgetary resources
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/tests/integration/test_federal_account_total.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
Labels: hotfix

#2910 Downmerge Master -> QAT
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/tests/integration/test_federal_account_total.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
Labels: down merge

#2908 [DEV-6449] Fix sorting error
  usaspending_api/api_contracts/contracts/v2/reporting/agencies/overview.md
  usaspending_api/reporting/v2/views/agencies/overview.py
Labels: warmfix

#2913 Downmerge QAT -> DEV
  usaspending_api/api_contracts/contracts/v2/reporting/agencies/overview.md
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/tests/integration/test_federal_account_total.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/reporting/v2/views/agencies/overview.py
Labels: down merge

#2912 DEV-6408: Covid Page Download Updates
  usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
Labels: hotfix

#2916 HOTFIX: [DEV-6724] Fixing ES awards delete to lookup delete keys in ES by transaction key
  usaspending_api/etl/elasticsearch_loader_helpers/__init__.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/index_config.py
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
  usaspending_api/etl/tests/test_es_rapidloader.py
Labels: hotfix

#2917 Master -> QAT
  usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
  usaspending_api/etl/elasticsearch_loader_helpers/__init__.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/index_config.py
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
  usaspending_api/etl/tests/test_es_rapidloader.py
Labels: hotfix

#2925 [OPS-1624] Add 'R' to FABA COVID Index
  usaspending_api/awards/migrations/0078_auto_20210126_1817.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
Labels: hotfix

#2926 Downmerge Master -> QAT
  usaspending_api/awards/migrations/0078_auto_20210126_1817.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
Labels: down merge

#2928 Downmerge QAT -> DEV
  usaspending_api/awards/migrations/0078_auto_20210126_1817.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
Labels: down merge

#2931 HOTFIX: [DEV-6763] Extend list of award keys needing to be deleted
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
Labels: hotfix

#2935 [DEV-6767] Removing R from partial index
  usaspending_api/awards/migrations/0079_auto_20210128_2234.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
Labels: hotfix

#2932 Master -> QAT
  usaspending_api/awards/migrations/0079_auto_20210128_2234.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
Labels: down merge

#2936 Downmerge QAT -> DEV
  usaspending_api/awards/migrations/0079_auto_20210128_2234.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
Labels: down merge
