Repository fedspendingtransparency/usaspending-api, pull requests merged in 2021-08, with the labels that each got.

#3202 [DEV-7743] subaward CFDA performance enhancements
  usaspending_api/awards/migrations/0084_auto_20210805_1722.py
  usaspending_api/awards/models/transaction_fabs.py
  usaspending_api/awards/v2/filters/sub_award.py
Labels: hotfix, ready for review

#3207 [DEV-7509] Number of New Awards
  usaspending_api/agency/tests/integration/test_new_award_count.py
  usaspending_api/agency/v2/urls.py
  usaspending_api/agency/v2/views/agency_base.py
  usaspending_api/agency/v2/views/new_award_count.py
  usaspending_api/api_contracts/contracts/v2/agency/toptier_code/awards/new/count.md
  usaspending_api/api_docs/markdown/endpoints.md
  usaspending_api/common/query_with_filters.py
  usaspending_api/search/filters/elasticsearch/filter.py
  usaspending_api/search/filters/elasticsearch/naics.py
  usaspending_api/search/filters/elasticsearch/psc.py
  usaspending_api/search/filters/elasticsearch/tas.py
Labels: ready for review

#3210 [DEV-7743] Some additional performance changes for Subaward CFDA
  usaspending_api/awards/v2/filters/sub_award.py
Labels: hotfix, ready for review

#3212 Downmerge DEV-7743
  usaspending_api/awards/migrations/0084_auto_20210805_1722.py
  usaspending_api/awards/models/transaction_fabs.py
  usaspending_api/awards/v2/filters/sub_award.py
Labels: down merge

#3213 Downmerge DEV-7743
  usaspending_api/awards/migrations/0084_auto_20210805_1722.py
  usaspending_api/awards/models/transaction_fabs.py
  usaspending_api/awards/v2/filters/sub_award.py
Labels: down merge

#3208 [DEV-7501] Adds Endpoint for Sub-Agency/Offices Count
  usaspending_api/agency/tests/conftest.py
  usaspending_api/agency/tests/fixtures/sub_agency_data.py
  usaspending_api/agency/tests/integration/test_sub_agency.py
  usaspending_api/agency/tests/integration/test_sub_agency_count.py
  usaspending_api/agency/v2/urls.py
  usaspending_api/agency/v2/views/sub_agency.py
  usaspending_api/agency/v2/views/sub_agency_count.py
  usaspending_api/api_contracts/contracts/v2/agency/toptier_code/sub_agency/count.md
  usaspending_api/api_docs/markdown/endpoints.md
  usaspending_api/common/elasticsearch/aggregation_helpers.py
Labels: ready for review

#3221 [DEV-7854] Fix dabs window loader to allow new records
  usaspending_api/submissions/management/commands/load_dabs_submission_window_schedule.py
  usaspending_api/submissions/tests/test_load_dabs_submission_window_schedule.py
Labels: hotfix, ready for review

#3220 [DEV-7773] Fix award summary page download to avoid empty columns
  usaspending_api/accounts/v2/filters/account_download.py
  usaspending_api/awards/v2/filters/award_filters.py
  usaspending_api/awards/v2/filters/idv_filters.py
  usaspending_api/submissions/helpers.py
Labels: ready for review
