Repository fedspendingtransparency/usaspending-api, pull requests merged in 2021-03, with the labels that each got.

#3005 [FIX] Removed potential for divide by zero error in log statement
  usaspending_api/transactions/agnostic_transaction_loader.py
Labels: warmfix

#3006 Small cleanup around ES ETL config
  usaspending_api/conftest_helpers.py
  usaspending_api/etl/es_config_objects.json
  usaspending_api/etl/management/commands/es_configure.py
Labels: warmfix

#3007 [DEV-6942] Award summary page covid outlay correction
  usaspending_api/awards/tests/test_awards_v2.py
  usaspending_api/awards/v2/data_layer/sql.py
Labels: warmfix

#3002 [DEV-6932] Update downloads to use new COVID outlay calculation
  usaspending_api/download/helpers/disaster_filter_functions.py
  usaspending_api/download/helpers/download_annotation_functions.py
Labels: warmfix

#3009 Downmerge Staging -> QAT
  usaspending_api/conftest_helpers.py
  usaspending_api/etl/es_config_objects.json
  usaspending_api/etl/management/commands/es_configure.py
  usaspending_api/transactions/agnostic_transaction_loader.py
Labels: down merge

#3004 [DEV-6936] Updates to DABS ETL for loading additional File C records
  usaspending_api/etl/management/sql/dev3627_compare_dabs_row_counts.sql
  usaspending_api/etl/submission_loader_helpers/file_c.py
  usaspending_api/etl/tests/integration/test_load_multiple_submissions.py
Labels: warmfix

#3010 Staging -> QAT
  usaspending_api/etl/management/sql/dev3627_compare_dabs_row_counts.sql
  usaspending_api/etl/submission_loader_helpers/file_c.py
  usaspending_api/etl/tests/integration/test_load_multiple_submissions.py
Labels: down merge

#3011 QAT -> Dev
  usaspending_api/awards/tests/test_awards_v2.py
  usaspending_api/awards/v2/data_layer/sql.py
  usaspending_api/conftest_helpers.py
  usaspending_api/disaster/tests/fixtures/overview_data.py
  usaspending_api/disaster/v2/views/overview.py
  usaspending_api/download/helpers/disaster_filter_functions.py
  usaspending_api/download/helpers/download_annotation_functions.py
  usaspending_api/etl/es_config_objects.json
  usaspending_api/etl/management/commands/es_configure.py
  usaspending_api/etl/management/sql/dev3627_compare_dabs_row_counts.sql
  usaspending_api/etl/submission_loader_helpers/file_c.py
  usaspending_api/etl/tests/integration/test_load_multiple_submissions.py
  usaspending_api/reporting/tests/integration/test_agencies_overview.py
  usaspending_api/reporting/tests/integration/test_agency_code_overview.py
  usaspending_api/reporting/v2/views/agencies/overview.py
  usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py
  usaspending_api/transactions/agnostic_transaction_loader.py
Labels: down merge

#3003 [DEV-6922] Fix outlay calculations
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/fixtures/object_class_data.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/tests/integration/test_federal_account_award.py
  usaspending_api/disaster/tests/integration/test_object_class_spending_award.py
  usaspending_api/disaster/v2/views/elasticsearch_account_base.py
  usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
Labels: warmfix

#3012 [DEV-6923] Add new fields to Custom Account Download
  usaspending_api/accounts/v2/filters/account_download.py
  usaspending_api/download/v2/download_column_historical_lookups.py
Labels: warmfix

#3008 [DEV-6921] Updates Covid Downloads - File A, B, D
  usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_b.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
Labels: warmfix

#3015 Mod/dev 6931 update es award index calculations for total covid outlay
  usaspending_api/database_scripts/matview_generator/mv_contract_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_directpayment_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_grant_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_idv_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_loan_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_other_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_pre2008_award_search.json
Labels: warmfix

#2978 [OPS-1657] ddtrace update and subprocess and sub-step tracing of Bulk Downloader
  Dockerfile
  requirements/requirements-app.txt
  usaspending_api/common/datadog.py
  usaspending_api/common/helpers/s3_helpers.py
  usaspending_api/common/tests/unit/test_tracing.py
  usaspending_api/common/tracing.py
  usaspending_api/download/filestreaming/download_generation.py
  usaspending_api/download/management/commands/download_sqs_worker.py
  usaspending_api/settings.py
Labels: ready for review

#3020 [DEV-6923] Adjust filtering to take into account new columns that affect outlay calculations
  usaspending_api/accounts/v2/filters/account_download.py
  usaspending_api/disaster/v2/views/disaster_base.py
Labels: warmfix

#3019 [FIX] issue with pandas API
  usaspending_api/download/management/commands/populate_monthly_delta_files.py
Labels: warmfix

#3025 [DEV-7004] Outlay calculation fix
  usaspending_api/database_scripts/matview_generator/mv_covid_financial_account.json
  usaspending_api/disaster/v2/views/disaster_base.py
Labels: warmfix

#3027 [DEV-7025] Remove Financing Accounts from GTAS data
  usaspending_api/references/management/commands/load_gtas.py
  usaspending_api/references/tests/data/broker_gtas.json
  usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py
Labels: warmfix

#3029 [DEV-7012] Change how Awards with negated outlay are filtered out
  usaspending_api/common/query_with_filters.py
  usaspending_api/disaster/tests/integration/test_object_class_spending_award.py
  usaspending_api/disaster/v2/views/elasticsearch_account_base.py
Labels: warmfix

#3030 Staging -> QAT
  usaspending_api/common/query_with_filters.py
  usaspending_api/database_scripts/matview_generator/mv_covid_financial_account.json
  usaspending_api/disaster/tests/integration/test_object_class_spending_award.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/disaster/v2/views/elasticsearch_account_base.py
  usaspending_api/references/management/commands/load_gtas.py
  usaspending_api/references/tests/data/broker_gtas.json
  usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py
Labels: do not merge, down merge

#3031 [DEV-6957] Adding new SQL view for only toptier agencies with DABS
  usaspending_api/references/migrations/0052_toptieragencypublisheddabsview.py
  usaspending_api/references/models/__init__.py
  usaspending_api/references/models/toptier_agency_published_dabs_view.py
  usaspending_api/settings.py
Labels: warmfix

#3036 Add new fields in the outlay calculations to FABA index
  usaspending_api/awards/migrations/0079_auto_20210315_1946.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
Labels: warmfix

#3037 Downmerge Staging -> QAT
  usaspending_api/awards/migrations/0079_auto_20210315_1946.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
Labels: down merge

#3032 [DEV-6957] Leverage new SQL View to return the subset of Agencies with published DABS
  usaspending_api/agency/tests/integration/conftest.py
  usaspending_api/agency/tests/integration/test_agency.py
  usaspending_api/agency/tests/integration/test_agency_budgetary_resources.py
  usaspending_api/agency/v2/views/agency_base.py
  usaspending_api/references/models/toptier_agency.py
  usaspending_api/reporting/management/commands/populate_reporting_agency_overview.py
  usaspending_api/reporting/tests/integration/test_agencies_overview.py
  usaspending_api/reporting/tests/integration/test_agencies_publish_dates.py
  usaspending_api/reporting/tests/integration/test_differences_endpoint.py
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_overview.py
  usaspending_api/reporting/v2/views/agencies/overview.py
  usaspending_api/reporting/v2/views/agencies/publish_dates.py
  usaspending_api/reporting/v2/views/agencies/toptier_code/differences.py
  usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py
Labels: warmfix

#3033 QAT -> DEV
  usaspending_api/agency/tests/integration/conftest.py
  usaspending_api/agency/tests/integration/test_agency.py
  usaspending_api/agency/tests/integration/test_agency_budgetary_resources.py
  usaspending_api/agency/v2/views/agency_base.py
  usaspending_api/awards/migrations/0079_auto_20210315_1946.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
  usaspending_api/common/query_with_filters.py
  usaspending_api/database_scripts/matview_generator/mv_covid_financial_account.json
  usaspending_api/disaster/tests/integration/test_object_class_spending_award.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/disaster/v2/views/elasticsearch_account_base.py
  usaspending_api/references/management/commands/load_gtas.py
  usaspending_api/references/migrations/0052_toptieragencypublisheddabsview.py
  usaspending_api/references/models/__init__.py
  usaspending_api/references/models/toptier_agency.py
  usaspending_api/references/models/toptier_agency_published_dabs_view.py
  usaspending_api/references/tests/data/broker_gtas.json
  usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py
  usaspending_api/reporting/management/commands/populate_reporting_agency_overview.py
  usaspending_api/reporting/tests/integration/test_agencies_overview.py
  usaspending_api/reporting/tests/integration/test_agencies_publish_dates.py
  usaspending_api/reporting/tests/integration/test_differences_endpoint.py
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_overview.py
  usaspending_api/reporting/v2/views/agencies/overview.py
  usaspending_api/reporting/v2/views/agencies/publish_dates.py
  usaspending_api/reporting/v2/views/agencies/toptier_code/differences.py
  usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py
  usaspending_api/settings.py
Labels: down merge

#3041 dev-6982 reorder and change gross_outlay_amount to gross_outlay_amoun…
  usaspending_api/download/v2/download_column_historical_lookups.py
Labels: warmfix

#3044 [DEV-6921] Fixed oversights from including outlay adjustment fields
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
Labels: warmfix

#3034 [DEV-6957] Densely Populate ReportingAgencyOverview
  usaspending_api/reporting/management/commands/populate_reporting_agency_overview.py
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_overview.py
Labels: warmfix

#3046 Staging -> QAT
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
  usaspending_api/download/v2/download_column_historical_lookups.py
Labels: down merge

#3051 [FIX] corrected two issues in QAT
  usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py
  usaspending_api/reporting/tests/integration/test_agency_code_overview.py
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_overview.py
  usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py
Labels: warmfix

#3047 QAT -> Dev
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
  usaspending_api/download/v2/download_column_historical_lookups.py
  usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py
  usaspending_api/reporting/management/commands/populate_reporting_agency_overview.py
  usaspending_api/reporting/tests/integration/test_agency_code_overview.py
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_overview.py
  usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py
Labels: down merge

#3057 [DEV-7071] Fixed dearth of FKs in treasury_appropriation_account
  usaspending_api/etl/operations/treasury_appropriation_account/update_agencies.py
  usaspending_api/etl/tests/integration/test_account_update_agencies.py
  usaspending_api/reporting/management/commands/populate_reporting_agency_overview.py
  usaspending_api/reporting/v2/views/agencies/overview.py
Labels: warmfix

#3056 WARMFIX: [DEV-6756] Reducing batch size of the _delete_by_query on incremental index
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/load_data.py
Labels: ready for review, warmfix

#3058 Staging -> QAT
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/load_data.py
  usaspending_api/etl/operations/treasury_appropriation_account/update_agencies.py
  usaspending_api/etl/tests/integration/test_account_update_agencies.py
  usaspending_api/reporting/management/commands/populate_reporting_agency_overview.py
  usaspending_api/reporting/v2/views/agencies/overview.py
Labels: down merge

#3059 QAT -> Dev
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/load_data.py
  usaspending_api/etl/operations/treasury_appropriation_account/update_agencies.py
  usaspending_api/etl/tests/integration/test_account_update_agencies.py
  usaspending_api/reporting/management/commands/populate_reporting_agency_overview.py
  usaspending_api/reporting/v2/views/agencies/overview.py
Labels: down merge

#3064 [DEV-6567] Fix an oversight with Keyword Search validation changes
  usaspending_api/download/v2/request_validations.py
Labels: warmfix

#3066 [Fix] Fixed agency grouping of TAS data for About the Data
  usaspending_api/etl/operations/treasury_appropriation_account/update_agencies.py
  usaspending_api/etl/tests/integration/test_account_update_agencies.py
  usaspending_api/reporting/management/commands/populate_reporting_agency_overview.py
  usaspending_api/reporting/management/sql/populate_reporting_agency_missing_tas.sql
  usaspending_api/reporting/management/sql/populate_reporting_agency_tas.sql
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_missing_tas.py
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_overview.py
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_tas.py
Labels: warmfix

#3070 Downmerge Staging -> QAT
  usaspending_api/agency/tests/integration/test_agency_budgetary_resources.py
  usaspending_api/agency/v2/views/budgetary_resources.py
Labels: down merge

#3069 Downmerge QAT -> Dev
  usaspending_api/agency/tests/integration/test_agency_budgetary_resources.py
  usaspending_api/agency/v2/views/budgetary_resources.py
  usaspending_api/download/v2/request_validations.py
  usaspending_api/etl/operations/treasury_appropriation_account/update_agencies.py
  usaspending_api/etl/tests/integration/test_account_update_agencies.py
  usaspending_api/reporting/management/commands/populate_reporting_agency_overview.py
  usaspending_api/reporting/management/sql/populate_reporting_agency_missing_tas.sql
  usaspending_api/reporting/management/sql/populate_reporting_agency_tas.sql
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_missing_tas.py
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_overview.py
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_tas.py
Labels: down merge

#3067 [WARMFIX] Fix calculation of total_budgetary_resources for publish_dates
  usaspending_api/reporting/tests/integration/test_agencies_publish_dates.py
  usaspending_api/reporting/v2/views/agencies/publish_dates.py
Labels: warmfix

#3077 QAT->DEV Downmerge
  usaspending_api/reporting/tests/integration/test_agencies_publish_dates.py
  usaspending_api/reporting/v2/views/agencies/publish_dates.py
Labels: ready for review
