Repository fedspendingtransparency/usaspending-api, pull requests merged in 2021-02, with the labels that each got.

#2946 [Warmfix] Follows pattern for deleting stale fabs/fpds to also delete transaction_search
  usaspending_api/broker/helpers/delete_stale_fabs.py
  usaspending_api/conftest.py
  usaspending_api/etl/transaction_loaders/fpds_loader.py
Labels: warmfix

#2950 DDtrace Agent back to 0.37.1
  requirements/requirements-app.txt
Labels: warmfix

#2951 Staging -> QAT
  requirements/requirements-app.txt
Labels: down merge

#2949 QAT -> DEV
  requirements/requirements-app.txt
  usaspending_api/broker/helpers/delete_stale_fabs.py
  usaspending_api/conftest.py
  usaspending_api/etl/transaction_loaders/fpds_loader.py
Labels: down merge

#2929 [DEV-6756] Speedup ES ETL delete sync using terms query and keyword fields
  usaspending_api/conftest.py
  usaspending_api/conftest_helpers.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/load_data.py
  usaspending_api/etl/es_award_template.json
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
  usaspending_api/etl/tests/test_elasticsearch_indexer.py
  usaspending_api/etl/tests/unit/elasticsearch_loader_helpers/test_controller.py
Labels: ready for review

#2963 [FIX] Augment tempfile.SpooledTemporaryFile() for expected behavior
  usaspending_api/common/retrieve_file_from_uri.py
  usaspending_api/common/tests/integration/test_retrieve_from_file_uri.py
Labels: warmfix

#2966 Fix broken test cases
  usaspending_api/reporting/tests/integration/test_agencies_overview.py
  usaspending_api/settings.py
Labels: hotfix

#2965 [DEV-6880] Update RecipientLookup PK to use BigAutoField
  usaspending_api/recipient/migrations/0004_auto_20210216_1341.py
  usaspending_api/recipient/models.py
Labels: do not merge, hotfix

#2969 [DEV-6880] Update recipient profile PK to BigInt
  usaspending_api/recipient/migrations/0005_auto_20210216_2120.py
  usaspending_api/recipient/models.py
Labels: hotfix

#2967 Downmerge Master -> QAT
  usaspending_api/recipient/migrations/0004_auto_20210216_1341.py
  usaspending_api/recipient/migrations/0005_auto_20210216_2120.py
  usaspending_api/recipient/models.py
  usaspending_api/reporting/tests/integration/test_agencies_overview.py
  usaspending_api/settings.py
Labels: down merge

#2971 Downmerge QAT -> DEV
  usaspending_api/recipient/migrations/0004_auto_20210216_1341.py
  usaspending_api/recipient/migrations/0005_auto_20210216_2120.py
  usaspending_api/recipient/models.py
  usaspending_api/reporting/tests/integration/test_agencies_overview.py
  usaspending_api/settings.py
Labels: down merge

#2973 [DEV-6534] Add Missing Submission history to endpoint
  usaspending_api/etl/management/commands/load_submission.py
  usaspending_api/reporting/tests/integration/test_agencies_submission_history.py
  usaspending_api/reporting/v2/views/submission_history.py
Labels: warmfix

#2962 [DEV-6798] new migration to include U in partial index
  usaspending_api/awards/migrations/0078_auto_20210126_1817.py
  usaspending_api/awards/migrations/0078_auto_20210211_2237.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
Labels: hotfix, ready for review

#2961 [DEV-6723] Adding DEFC U to API contracts
  usaspending_api/api_contracts/contracts/v2/disaster/agency/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/agency/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/agency/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/award/amount.md
  usaspending_api/api_contracts/contracts/v2/disaster/award/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/def_code/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/federal_account/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/federal_account/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/federal_account/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/object_class/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/object_class/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/object_class/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/overview.md
  usaspending_api/api_contracts/contracts/v2/disaster/recipient/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/recipient/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/recipient/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/spending_by_geography.md
  usaspending_api/api_contracts/contracts/v2/download/disaster.md
  usaspending_api/api_contracts/contracts/v2/download/disaster/recipients.md
  usaspending_api/api_contracts/contracts/v2/references/def_codes.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
Labels: hotfix, ready for review

#2975 Master -> Staging
  usaspending_api/api_contracts/contracts/v2/disaster/agency/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/agency/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/agency/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/award/amount.md
  usaspending_api/api_contracts/contracts/v2/disaster/award/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/def_code/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/federal_account/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/federal_account/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/federal_account/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/object_class/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/object_class/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/object_class/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/overview.md
  usaspending_api/api_contracts/contracts/v2/disaster/recipient/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/recipient/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/recipient/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/spending_by_geography.md
  usaspending_api/api_contracts/contracts/v2/download/disaster.md
  usaspending_api/api_contracts/contracts/v2/download/disaster/recipients.md
  usaspending_api/api_contracts/contracts/v2/references/def_codes.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
  usaspending_api/awards/migrations/0078_auto_20210126_1817.py
  usaspending_api/awards/migrations/0078_auto_20210211_2237.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
Labels: down merge

#2977 QAT -> DEV
  usaspending_api/api_contracts/contracts/v2/disaster/agency/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/agency/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/agency/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/award/amount.md
  usaspending_api/api_contracts/contracts/v2/disaster/award/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/cfda/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/def_code/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/federal_account/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/federal_account/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/federal_account/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/object_class/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/object_class/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/object_class/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/overview.md
  usaspending_api/api_contracts/contracts/v2/disaster/recipient/count.md
  usaspending_api/api_contracts/contracts/v2/disaster/recipient/loans.md
  usaspending_api/api_contracts/contracts/v2/disaster/recipient/spending.md
  usaspending_api/api_contracts/contracts/v2/disaster/spending_by_geography.md
  usaspending_api/api_contracts/contracts/v2/download/disaster.md
  usaspending_api/api_contracts/contracts/v2/download/disaster/recipients.md
  usaspending_api/api_contracts/contracts/v2/references/def_codes.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
  usaspending_api/awards/migrations/0078_auto_20210126_1817.py
  usaspending_api/awards/migrations/0078_auto_20210211_2237.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
  usaspending_api/common/retrieve_file_from_uri.py
  usaspending_api/common/tests/integration/test_retrieve_from_file_uri.py
  usaspending_api/etl/management/commands/load_submission.py
  usaspending_api/reporting/tests/integration/test_agencies_submission_history.py
  usaspending_api/reporting/v2/views/submission_history.py
Labels: down merge

#2993 [DEV-6907] multi-year calculations epic hotfixes
  usaspending_api/common/etl/mixins.py
  usaspending_api/disaster/tests/conftest.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/fixtures/object_class_data.py
  usaspending_api/disaster/tests/fixtures/overview_data.py
  usaspending_api/disaster/tests/integration/test_overview.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/object_class/spending.py
  usaspending_api/disaster/v2/views/overview.py
  usaspending_api/references/management/commands/load_gtas.py
  usaspending_api/references/migrations/0051_auto_20210223_1404.py
  usaspending_api/references/models/gtas_sf133_balances.py
  usaspending_api/references/tests/data/broker_gtas.json
  usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py
Labels: do not merge, hotfix

#2994 Master -> Staging
  usaspending_api/common/etl/mixins.py
  usaspending_api/disaster/tests/conftest.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/fixtures/object_class_data.py
  usaspending_api/disaster/tests/fixtures/overview_data.py
  usaspending_api/disaster/tests/integration/test_overview.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/object_class/spending.py
  usaspending_api/disaster/v2/views/overview.py
  usaspending_api/references/management/commands/load_gtas.py
  usaspending_api/references/migrations/0051_auto_20210223_1404.py
  usaspending_api/references/models/gtas_sf133_balances.py
  usaspending_api/references/tests/data/broker_gtas.json
  usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py
Labels: down merge

#2995 Staging -> QAT
  usaspending_api/common/etl/mixins.py
  usaspending_api/disaster/tests/conftest.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/fixtures/object_class_data.py
  usaspending_api/disaster/tests/fixtures/overview_data.py
  usaspending_api/disaster/tests/integration/test_overview.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/object_class/spending.py
  usaspending_api/disaster/v2/views/overview.py
  usaspending_api/references/management/commands/load_gtas.py
  usaspending_api/references/migrations/0051_auto_20210223_1404.py
  usaspending_api/references/models/gtas_sf133_balances.py
  usaspending_api/references/tests/data/broker_gtas.json
  usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py
Labels: down merge

#2996 QAT -> Dev
  usaspending_api/common/etl/mixins.py
  usaspending_api/disaster/tests/conftest.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/fixtures/object_class_data.py
  usaspending_api/disaster/tests/fixtures/overview_data.py
  usaspending_api/disaster/tests/integration/test_overview.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/disaster_base.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/object_class/spending.py
  usaspending_api/disaster/v2/views/overview.py
  usaspending_api/references/management/commands/load_gtas.py
  usaspending_api/references/migrations/0051_auto_20210223_1404.py
  usaspending_api/references/models/gtas_sf133_balances.py
  usaspending_api/references/tests/data/broker_gtas.json
  usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py
Labels: down merge

#3000 [DEV-6920] Updates award outlay calculation on disaster overview endpoint
  usaspending_api/disaster/tests/fixtures/overview_data.py
  usaspending_api/disaster/v2/views/overview.py
Labels: warmfix

#3001 [DEV-6948] Stop generating assurance urls for non-existent submissions
  usaspending_api/reporting/tests/integration/test_agencies_overview.py
  usaspending_api/reporting/tests/integration/test_agency_code_overview.py
  usaspending_api/reporting/v2/views/agencies/overview.py
  usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py
Labels: warmfix

#2999 Downmerge Staging -> QAT
  usaspending_api/reporting/tests/integration/test_agencies_overview.py
  usaspending_api/reporting/tests/integration/test_agency_code_overview.py
  usaspending_api/reporting/v2/views/agencies/overview.py
  usaspending_api/reporting/v2/views/agencies/toptier_code/overview.py
Labels: down merge
