Repository fedspendingtransparency/usaspending-api, pull requests merged in 2022-03, with the labels that each got.

#3393 Updating marshmallow version
  requirements/requirements-app.txt
Labels: hotfix

#3394 Downmerge change to marshmellow version
  requirements/requirements-app.txt
Labels: down merge

#3395 Downmerge marshmallow version update
  requirements/requirements-app.txt
Labels: down merge

#3392 [DEV-8473] Add UEI to subaward related bits
  usaspending_api/awards/management/commands/load_subawards_sql/030_frame_out_subawards.sql
  usaspending_api/awards/migrations/0091_auto_20220314_1432.py
  usaspending_api/awards/models/broker_subaward.py
  usaspending_api/awards/models/subaward.py
  usaspending_api/common/recipient_lookups.py
  usaspending_api/database_scripts/matview_generator/subaward_view.json
  usaspending_api/search/models/subaward_view.py
Labels: ready for review

#3398 [DEV-8585] Adds UEI to Keyword Filter for Subawards in Advanced Search
  usaspending_api/awards/tests/unit/test_subaward_filter.py
  usaspending_api/awards/v2/filters/sub_award.py
Labels: ready for review

#3397 [DEV-8584] add UEI to subawards filter
  usaspending_api/awards/v2/filters/sub_award.py
  usaspending_api/search/tests/data/spending_by_award_test_data.py
  usaspending_api/search/tests/integration/test_spending_by_award.py
Labels: ready for review

#3400 [DEV-7948] Ensure UEI related fields are available in subaward downloads
  usaspending_api/bulk_download/tests/test_download.py
  usaspending_api/download/v2/download_column_historical_lookups.py
Labels: ready for review

#3396 [DEV-8476] Update recipient level logic
  usaspending_api/awards/tests/test_awards_v2.py
  usaspending_api/awards/v2/data_layer/orm.py
  usaspending_api/common/recipient_lookups.py
  usaspending_api/common/tests/unit/test_recipient_lookup.py
  usaspending_api/etl/elasticsearch_loader_helpers/aggregate_key_functions.py
  usaspending_api/idvs/tests/test_awards_idv_v2.py
  usaspending_api/idvs/v2/views/activity.py
  usaspending_api/search/v2/views/spending_by_award.py
Labels: ready for review
