Repository fedspendingtransparency/usaspending-api, pull requests merged in 2022-12, with the labels that each got.

#3651 [DEV-9120] COVID-19 custom download
  usaspending_api/disaster/management/sql/disaster_covid19_file_a.sql
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/overview.py
  usaspending_api/download/v2/download_column_historical_lookups.py
  usaspending_api/references/management/commands/load_gtas.py
  usaspending_api/references/migrations/0061_gtassf133balances_add_status_of_budgetary_resources_total_cpe_field.py
  usaspending_api/references/migrations/0062_gtassf133balances_rename_adjustments_to_unobligated_balance_fields.py
  usaspending_api/references/models/gtas_sf133_balances.py
  usaspending_api/references/tests/data/broker_gtas.json
  usaspending_api/references/tests/integration/test_load_gtas_mgmt_cmd.py
Labels: hotfix, ready for review

#3646 [PIPE-461] Transaction Search Agg Key Rework
  usaspending_api/agency/tests/fixtures/sub_agency_data.py
  usaspending_api/agency/v2/views/sub_agency.py
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
  usaspending_api/etl/elasticsearch_loader_helpers/aggregate_key_functions.py
  usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
  usaspending_api/recipient/v2/views/recipients.py
  usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_awarding_subagency.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_funding_subagency.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_recipient.py
  usaspending_api/search/tests/integration/test_spending_by_geography.py
  usaspending_api/search/tests/unit/test_spending_by_category.py
  usaspending_api/search/tests/unit/test_tas_search.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_agency_types.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_industry_codes.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_recipient.py
  usaspending_api/search/v2/views/spending_by_geography.py
Labels: ready for review

#3668 [HOTFIX-STAGING] [DEV-9400] Fix over-indentation in for-loop
  usaspending_api/agency/v2/views/sub_agency.py
Labels: ready for review, down merge

#3667 [HOTFIX] [DEV-9400] Fix over-indentation in for-loop
  usaspending_api/agency/v2/views/sub_agency.py
Labels: do not merge, hotfix
