Repository fedspendingtransparency/usaspending-api, pull requests merged in 2022-10, with the labels that each got.

#3603 Test Fix: Updating fixture to be time independent (Staging)
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
Labels: warmfix

#3602 Downmerge to QAT
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/etl/es_award_template.json
Labels: down merge

#3581 [PIPE-407/411/412] Additional TransactionSearch Fields (Delta)
  usaspending_api/agency/tests/fixtures/sub_agency_data.py
  usaspending_api/agency/tests/integration/test_awards.py
  usaspending_api/database_scripts/matview_generator/transaction_search.json
  usaspending_api/download/tests/integration/test_download_awards.py
  usaspending_api/download/tests/integration/test_download_count.py
  usaspending_api/download/tests/integration/test_download_disaster.py
  usaspending_api/download/tests/integration/test_download_status.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
  usaspending_api/search/tests/integration/test_spending_over_time.py
  usaspending_api/search/tests/unit/test_spending_by_category.py
  usaspending_api/search/tests/unit/test_tas_search.py
  usaspending_api/transactions/delta_models/transaction_search.py
Labels: ready for review

#3582 [PIPE-407/411/412] Additional TransactionSearch Fields (Postgres)
  usaspending_api/search/migrations/0014_additional_transaction_search_cols.py
  usaspending_api/search/models/transaction_search.py
Labels: ready for review

#3607 [DEV-9171] Subaward Download piid/fain, not award_id
  usaspending_api/download/v2/download_column_historical_lookups.py
Labels: hotfix

#3624 [DEV-9216] Subawards Spending Over Time Fix
  usaspending_api/search/v2/views/spending_over_time.py
Labels: hotfix

#3619 [PIPE-408] Award search updates
  usaspending_api/database_scripts/matview_generator/award_search.json
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/search/migrations/0015_auto_20221026_1505.py
  usaspending_api/search/models/award_search.py
Labels: ready for review
