Repository fedspendingtransparency/usaspending-api, pull requests merged in 2022-04, with the labels that each got.

#3409 [DEV-8461] Switch to using UEI instead of DUNS for new_awards_over_time
  usaspending_api/recipient/management/sql/restock_summary_award_recipient.sql
  usaspending_api/recipient/migrations/0018_auto_20220325_1625.py
  usaspending_api/recipient/models.py
  usaspending_api/search/tests/unit/test_new_awards_over_time.py
  usaspending_api/search/v2/views/new_awards_over_time.py
Labels: hotfix

#3410 [DEV-8643] Add parent_uei to keyword searchs
  usaspending_api/common/query_with_filters.py
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
  usaspending_api/database_scripts/matview_generator/mv_contract_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_directpayment_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_grant_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_idv_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_loan_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_other_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_pre2008_award_search.json
  usaspending_api/database_scripts/matview_generator/transaction_search.json
  usaspending_api/etl/es_award_template.json
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/search/migrations/0007_transactionsearch_parent_uei.py
  usaspending_api/search/models/transaction_search.py
  usaspending_api/search/tests/data/spending_by_award_test_data.py
  usaspending_api/search/tests/integration/test_spending_by_award.py
  usaspending_api/search/tests/integration/test_spending_by_transaction.py
Labels: hotfix

#3411 DEV-8611: entity data source from broker
  usaspending_api/awards/migrations/0092_transactionfpds_entity_data_source.py
  usaspending_api/awards/models/transaction_fpds.py
  usaspending_api/etl/transaction_loaders/field_mappings_fpds.py
  usaspending_api/transactions/migrations/0008_sourceprocurementtransaction_entity_data_source.py
  usaspending_api/transactions/models/source_procurement_transaction.py
  usaspending_api/transactions/tests/integration/test_procurement_etl.py
Labels: hotfix

#3416 [DEV-8660][HOTFIX] null duns hotfix
  usaspending_api/recipient/migrations/0019_auto_20220406_1311.py
  usaspending_api/recipient/migrations/0020_auto_20220406_1352.py
  usaspending_api/recipient/models.py
Labels: hotfix

#3419 Downmerge hotfix
  usaspending_api/recipient/migrations/0019_auto_20220406_1311.py
  usaspending_api/recipient/migrations/0020_auto_20220406_1352.py
  usaspending_api/recipient/models.py
Labels: down merge

#3424 Sprint 149 Production Deployment
  usaspending_api/agency/tests/integration/test_subcomponents.py
  usaspending_api/agency/v2/views/subcomponents.py
Labels: do not merge, ENV Promotion

#3437 Promote QAT -> Staging
  .travis.yml
  CONTRIBUTING.md
  README.md
  usaspending_api/agency/v2/views/recipients.py
  usaspending_api/api_contracts/contracts/v2/agency/toptier_code/recipients.md
  usaspending_api/broker/management/commands/update_duns.py
  usaspending_api/broker/management/sql/restock_duns.sql
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
Labels: ENV Promotion
