Repository fedspendingtransparency/usaspending-api, pull requests merged in 2022-07, with the labels that each got.

#3503 [STAGING] Remove atomicwrites from requirements
  requirements/requirements-app.txt
Labels: warmfix, ready for review

#3504 [QAT] Remove atomicwrites qat
  requirements/requirements-app.txt
Labels: ready for review

#3505 Update transaction search sql
  usaspending_api/etl/tests/integration/test_load_to_delta.py
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/transactions/delta_models/transaction_search.py
Labels: ready for review

#3497 PIPE-289: Delta -> Postgres command
  usaspending_api/common/helpers/spark_helpers.py
  usaspending_api/database_scripts/matview_generator/__init__.py
  usaspending_api/database_scripts/matview_generator/chunked_matview_sql_generator.py
  usaspending_api/database_scripts/matview_generator/shared_sql_generator.py
  usaspending_api/etl/management/commands/combine_transaction_search_chunks.py
  usaspending_api/etl/management/commands/copy_table_metadata.py
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/management/commands/load_table_from_delta.py
  usaspending_api/etl/management/commands/load_table_to_delta.py
  usaspending_api/etl/tests/integration/test_copy_table_metadata.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/search/delta_models/__init__.py
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/transactions/delta_models/__init__.py
  usaspending_api/transactions/delta_models/transaction_search.py
Labels: ready for review

#3512 Performance improvements for Transaction and Award Search
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/transactions/delta_models/transaction_search.py
Labels: ready for review

#3519 PIPE-291: Adding Award Search Table [1/2]
  usaspending_api/common/helpers/spark_helpers.py
  usaspending_api/common/matview_manager.py
  usaspending_api/conftest.py
  usaspending_api/database_scripts/matview_generator/award_search.json
  usaspending_api/disaster/tests/fixtures/recipient_location_data.py
  usaspending_api/etl/management/commands/copy_table_metadata.py
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/management/commands/load_table_to_delta.py
  usaspending_api/etl/tests/integration/test_copy_table_metadata.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/search/migrations/0008_awardsearch_table.py
  usaspending_api/search/models/__init__.py
  usaspending_api/search/models/award_search.py
Labels: ready for review

#3520 PIPE-291: Removing Award Search Views [2/2]
  usaspending_api/awards/tests/unit/test_location_filter_geocode.py
  usaspending_api/awards/v2/filters/search.py
  usaspending_api/common/helpers/orm_helpers.py
  usaspending_api/common/matview_manager.py
  usaspending_api/database_scripts/matview_generator/mv_contract_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_directpayment_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_grant_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_idv_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_loan_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_other_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_pre2008_award_search.json
  usaspending_api/database_scripts/matviews/drop_old_matviews.sql
  usaspending_api/database_scripts/matviews/refresh_matviews.sql
  usaspending_api/database_scripts/matviews/vacuum_matviews.sql
  usaspending_api/database_scripts/matviews/vw_award_search.sql
  usaspending_api/database_scripts/matviews/vw_es_award_search.sql
  usaspending_api/download/helpers/disaster_filter_functions.py
  usaspending_api/download/lookups.py
  usaspending_api/search/migrations/0009_awardsearch_view_drop.py
  usaspending_api/search/models/__init__.py
  usaspending_api/search/models/base_award_search.py
  usaspending_api/search/models/mv_contract_award_search.py
  usaspending_api/search/models/mv_directpayment_award_search.py
  usaspending_api/search/models/mv_grant_award_search.py
  usaspending_api/search/models/mv_idv_award_search.py
  usaspending_api/search/models/mv_loan_award_search.py
  usaspending_api/search/models/mv_other_award_search.py
  usaspending_api/search/models/mv_pre2008_award_search.py
  usaspending_api/search/models/vw_award_search.py
Labels: ready for review

#3502 [PROD] Remove atomicwrites from requirements
  requirements/requirements-app.txt
Labels: do not merge, hotfix, ready for review
