Repository fedspendingtransparency/usaspending-api, pull requests merged in 2022-09, with the labels that each got.

#3571 Fix: SubawardSearch File F SQL Explicit
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
Labels: warmfix

#3572 [HOTFIX] [DEV-9073] Fetch unique broker recipients by UEI
  usaspending_api/broker/management/sql/restock_duns.sql
Labels: hotfix, ready for review

#3573 [HOTFIX] [DEV-9073] Fetch unique broker recipients by UEI (staging-downmerge)
  usaspending_api/broker/management/sql/restock_duns.sql
Labels: do not merge

#3574 [HOTFIX] [DEV-9073] Fetch unique broker recipients by UEI (qat-downmerge)
  usaspending_api/broker/management/sql/restock_duns.sql
Labels: do not merge

#3585 [DEV-9070] undo name change
  usaspending_api/accounts/migrations/0006_rename_adjustments_to_unobligated_balance_brought_forward_cpe_appropriationaccountbalances_adjustmen.py
  usaspending_api/accounts/models/appropriation_account_balances.py
  usaspending_api/accounts/tests/test_federal_account_fy_snapshot_v2.py
  usaspending_api/accounts/views/federal_accounts_v2.py
  usaspending_api/common/long_to_terse.py
  usaspending_api/database_scripts/job_archive/management/commands/generate_cares_act_test_data_sqls/clone_submissions.sql
  usaspending_api/database_scripts/job_archive/management/commands/generate_cares_act_test_data_sqls/copy_submissions.sql
  usaspending_api/download/v2/download_column_historical_lookups.py
Labels: hotfix

#3586 Downmerge master to staging
  usaspending_api/accounts/migrations/0006_rename_adjustments_to_unobligated_balance_brought_forward_cpe_appropriationaccountbalances_adjustmen.py
  usaspending_api/accounts/models/appropriation_account_balances.py
  usaspending_api/accounts/tests/test_federal_account_fy_snapshot_v2.py
  usaspending_api/accounts/views/federal_accounts_v2.py
  usaspending_api/common/long_to_terse.py
  usaspending_api/database_scripts/job_archive/management/commands/generate_cares_act_test_data_sqls/clone_submissions.sql
  usaspending_api/database_scripts/job_archive/management/commands/generate_cares_act_test_data_sqls/copy_submissions.sql
  usaspending_api/download/v2/download_column_historical_lookups.py
Labels: down merge

#3592 Travis CI and Postgresql Install Fix
  .travis.yml
Labels: ready for review

#3595 Fix migrations to avoid new migrations from makemigrations
  usaspending_api/recipient/migrations/0024_recipient_profile_index_rename.py
  usaspending_api/search/migrations/0001_initial.py
  usaspending_api/search/migrations/0010_subaward_search.py
  usaspending_api/search/models/subaward_search.py
Labels: ready for review
