Repository fedspendingtransparency/usaspending-api, pull requests merged in 2022-08, with the labels that each got.

#3495 [PIPE-191] Include all files on pip install
  MANIFEST.in
  setup.py
Labels: ready for review

#3536 [PIPE-10] pyspark as dev dependency only
  .env.template
  .gitignore
  .travis.yml
  Makefile
  README.md
  requirements/requirements-app.txt
  requirements/requirements-dev.txt
  requirements/requirements.txt
  setup.cfg
Labels: ready for review

#3534 Updating JSONB columns in Delta model postgres columns appropriately
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/transactions/delta_models/transaction_search.py
Labels: ready for review

#3537 [PIPE-325] raw.broker_subaward on delta
  .env.template
  usaspending_api/awards/delta_models/__init__.py
  usaspending_api/awards/delta_models/broker_subawards.py
  usaspending_api/common/helpers/spark_helpers.py
  usaspending_api/config/envs/default.py
  usaspending_api/config/envs/local.py
  usaspending_api/config/tests/unit/test_config.py
  usaspending_api/conftest.py
  usaspending_api/conftest_helpers.py
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/management/commands/load_table_from_delta.py
  usaspending_api/etl/management/commands/load_table_to_delta.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
Labels: ready for review

#3540 [PIPE-380] SQL bulk COPY of CSV to write Delta tables back to Postgres
  .env.template
  Makefile
  docker-compose.yml
  usaspending_api/common/csv_stream_s3_to_pg.py
  usaspending_api/common/etl/spark.py
  usaspending_api/common/helpers/spark_helpers.py
  usaspending_api/common/logging.py
  usaspending_api/config/envs/default.py
  usaspending_api/config/envs/local.py
  usaspending_api/config/envs/production.py
  usaspending_api/config/envs/qat.py
  usaspending_api/config/envs/staging.py
  usaspending_api/config/utils.py
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/management/commands/load_table_from_delta.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/etl/tests/integration/test_spark_app.py
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/settings.py
  usaspending_api/tests/conftest_spark.py
Labels: ready for review

#3538 [PIPE-10] More guards on make clean-all to not remove custom setup files
  Makefile
Labels: ready for review

#3527 Updated to swap command logging and additional validation check
  usaspending_api/etl/management/commands/swap_in_new_table.py
  usaspending_api/etl/tests/integration/test_swap_in_new_table.py
Labels: ready for review

#3545 [OPS-2361] Implement delta for uwsgi max lifetime restart
  config/uwsgi.ini
Labels: ready for review

#3546 [OPS-2361] Add missing newline
  config/uwsgi.ini
Labels: ready for review

#3542 [PIPE-380] Fix lost backslashes in array elements
  usaspending_api/common/etl/spark.py
Labels: ready for review

#3549 Sprint 155 Prod Deployment
  .env.template
  .gitignore
  .travis.yml
  MANIFEST.in
  Makefile
  README.md
  config/uwsgi.ini
  docker-compose.yml
  requirements/requirements-app.txt
  requirements/requirements-dev.txt
  requirements/requirements.txt
  setup.cfg
  setup.py
  usaspending_api/api_docs/markdown/endpoints.md
  usaspending_api/awards/delta_models/__init__.py
  usaspending_api/awards/delta_models/broker_subawards.py
  usaspending_api/common/csv_stream_s3_to_pg.py
  usaspending_api/common/etl/spark.py
  usaspending_api/common/helpers/spark_helpers.py
  usaspending_api/common/logging.py
  usaspending_api/config/envs/default.py
  usaspending_api/config/envs/local.py
  usaspending_api/config/envs/production.py
  usaspending_api/config/envs/qat.py
  usaspending_api/config/envs/staging.py
  usaspending_api/config/tests/unit/test_config.py
  usaspending_api/config/utils.py
  usaspending_api/conftest.py
  usaspending_api/conftest_helpers.py
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/management/commands/load_table_from_delta.py
  usaspending_api/etl/management/commands/load_table_to_delta.py
  usaspending_api/etl/management/commands/swap_in_new_table.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/etl/tests/integration/test_spark_app.py
  usaspending_api/etl/tests/integration/test_swap_in_new_table.py
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/settings.py
  usaspending_api/tests/conftest_spark.py
  usaspending_api/transactions/delta_models/transaction_search.py
Labels: ENV Promotion

#3550 [DEV-9043] Fixing the CFDA filter to account for whitespace in regex
  usaspending_api/common/query_with_filters.py
Labels: hotfix, ready for review

#3541 [PIPE-315] Implement Recipient Lookup ETL with Spark
  Makefile
  README.md
  usaspending_api/etl/management/commands/create_delta_table.py
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/management/commands/load_table_to_delta.py
  usaspending_api/etl/tests/integration/test_create_delta_table.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/recipient/delta_models/__init__.py
  usaspending_api/recipient/delta_models/recipient_lookup.py
Labels: ready for review

#3553 Downmerge DEV-9043 into QAT
  usaspending_api/common/query_with_filters.py
Labels: down merge

#3551 [PIPE-373] updated current spark ETLs to use new rpt.recipient_lookup
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/management/commands/load_table_to_delta.py
  usaspending_api/etl/tests/integration/test_create_delta_table.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/recipient/delta_models/recipient_profile.py
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/transactions/delta_models/transaction_search.py
Labels: ready for review

#3544 [PIPE-327] Delta raw.broker_subaward -> rpt.subaward_search
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/tests/integration/conftest.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta_subawards.py
  usaspending_api/search/delta_models/__init__.py
  usaspending_api/search/delta_models/subaward_search.py
Labels: ready for review

#3558 [PIPE-327] Renaming Delta raw.broker_subaward to raw.subaward
  usaspending_api/awards/tests/data/subaward.json
  usaspending_api/awards/tests/integration/test_load_subawards.py
  usaspending_api/etl/management/commands/load_table_to_delta.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta_subawards.py
  usaspending_api/search/delta_models/subaward_search.py
Labels: ready for review

#3555 [PIPE-322] Few changes to allow copy back of Recipient Lookup
  .travis.yml
  docker-compose.yml
  usaspending_api/etl/management/commands/copy_table_metadata.py
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/management/commands/load_table_from_delta.py
  usaspending_api/etl/tests/integration/conftest.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta_subawards.py
  usaspending_api/recipient/delta_models/__init__.py
  usaspending_api/recipient/delta_models/recipient_lookup.py
Labels: ready for review

#3517 [Pipe 313] summary state view create lakehouse tables
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/tests/integration/test_create_delta_table.py
  usaspending_api/transactions/delta_models/__init__.py
  usaspending_api/transactions/delta_models/summary_state_view.py
Labels: ready for review

#3561 [PIPE-314] Create summary_state_view as Spark ETL
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/transactions/delta_models/__init__.py
  usaspending_api/transactions/delta_models/summary_state_view.py
Labels: ready for review

#3563 [PIPE-321] Copy back summary_state_view from Delta to Postgres
  usaspending_api/database_scripts/matview_generator/summary_state_view.json
  usaspending_api/database_scripts/matviews/drop_old_matviews.sql
  usaspending_api/database_scripts/matviews/refresh_matviews.sql
  usaspending_api/database_scripts/matviews/vacuum_matviews.sql
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/management/commands/swap_in_new_table.py
  usaspending_api/etl/migrations/0002_summary_state_view_schema_change.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/search/migrations/0011_alter_summarystateview_options.py
  usaspending_api/search/models/summary_state_view.py
  usaspending_api/transactions/delta_models/__init__.py
  usaspending_api/transactions/delta_models/summary_state_view.py
Labels: ready for review

#3559 [PIPE-328] update_delta_award_with_subaward_counts command
  usaspending_api/awards/tests/data/subaward.json
  usaspending_api/etl/management/commands/update_delta_award_with_subaward_counts.py
  usaspending_api/etl/management/commands/update_postgres_award_with_subaward_counts.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta_subawards.py
Labels: ready for review
