Repository fedspendingtransparency/usaspending-api, pull requests merged in 2022-05, with the labels that each got.

#3438 Sprint 150 Production Deploy
  .travis.yml
  CONTRIBUTING.md
  README.md
  usaspending_api/agency/v2/views/recipients.py
  usaspending_api/api_contracts/contracts/v2/agency/toptier_code/recipients.md
  usaspending_api/broker/management/commands/update_duns.py
  usaspending_api/broker/management/sql/restock_duns.sql
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
Labels: ENV Promotion

#3441 DEV-8751: Removing covid_19 DEFC filter from endpoints with grouped outlays
  usaspending_api/awards/tests/test_awards_v2.py
  usaspending_api/awards/v2/data_layer/orm.py
  usaspending_api/awards/v2/data_layer/sql.py
  usaspending_api/idvs/v2/views/amounts.py
Labels: ready for review

#3452 [PIPE-10] setup.py only build metadata
  pyproject.toml
  setup.py
Labels: ready for review

#3445 [PIPE-10] Use `make` or `make help` to print help docs for targets
  Makefile
Labels: ready for review

#3453 [PIPE-10] Allow child root_validators to override parent field defaults
  usaspending_api/config/envs/default.py
  usaspending_api/config/envs/local.py
  usaspending_api/config/tests/unit/test_config.py
  usaspending_api/config/utils.py
Labels: ready for review

#3444 [PIPE-269] Move count endpoints to ES
  usaspending_api/awards/migrations/0094_delete_covidfinancialaccountmatview.py
  usaspending_api/awards/models/__init__.py
  usaspending_api/awards/models/mv_covid_financial_account.py
  usaspending_api/common/matview_manager.py
  usaspending_api/database_scripts/matview_generator/mv_covid_financial_account.json
  usaspending_api/disaster/tests/fixtures/agency_count_data.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/recipient_count_data.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_count.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/tests/integration/test_disaster_recipient_count.py
  usaspending_api/disaster/v2/views/agency/count.py
  usaspending_api/disaster/v2/views/recipient/count.py
Labels: ready for review

#3426 [PIPE-192] Move different tables into schemas to align with new architecture changes
  .travis.yml
  usaspending_api/awards/management/commands/load_subawards.py
  usaspending_api/broker/management/sql/restock_duns.sql
  usaspending_api/database_scripts/matview_generator/chunked_matview_sql_generator.py
  usaspending_api/database_scripts/matview_generator/matview_sql_generator.py
  usaspending_api/database_scripts/matview_generator/mv_contract_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_directpayment_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_grant_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_idv_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_loan_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_other_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_pre2008_award_search.json
  usaspending_api/database_scripts/matview_generator/subaward_view.json
  usaspending_api/database_scripts/matview_generator/transaction_search.json
  usaspending_api/database_scripts/matviews/vw_award_search.sql
  usaspending_api/etl/management/commands/combine_transaction_search_chunks.py
  usaspending_api/etl/migrations/0001_create_schemas.py
  usaspending_api/etl/migrations/__init__.py
  usaspending_api/recipient/management/sql/recipient_lookup/100_finalize.sql
  usaspending_api/recipient/management/sql/restock_recipient_profile.sql
  usaspending_api/transactions/agnostic_transaction_loader.py
Labels: ready for review

#3458 [PIPE-182] Unit tests for delta table creation and loading
  .env.template
  .travis.yml
  Dockerfile.spark
  docker-compose.yml
  usaspending_api/awards/management/commands/load_subawards.py
  usaspending_api/broker/management/sql/restock_duns.sql
  usaspending_api/config/envs/default.py
  usaspending_api/config/envs/local.py
  usaspending_api/database_scripts/matview_generator/chunked_matview_sql_generator.py
  usaspending_api/database_scripts/matview_generator/matview_sql_generator.py
  usaspending_api/database_scripts/matview_generator/mv_contract_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_directpayment_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_grant_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_idv_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_loan_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_other_award_search.json
  usaspending_api/database_scripts/matview_generator/mv_pre2008_award_search.json
  usaspending_api/database_scripts/matview_generator/subaward_view.json
  usaspending_api/database_scripts/matview_generator/transaction_search.json
  usaspending_api/database_scripts/matviews/vw_award_search.sql
  usaspending_api/etl/management/commands/combine_transaction_search_chunks.py
  usaspending_api/etl/migrations/0001_create_schemas.py
  usaspending_api/etl/migrations/__init__.py
  usaspending_api/etl/tests/conftest.py
  usaspending_api/etl/tests/conftest_spark.py
  usaspending_api/etl/tests/integration/test_create_delta_table.py
  usaspending_api/etl/tests/integration/test_spark_app.py
  usaspending_api/recipient/management/sql/recipient_lookup/100_finalize.sql
  usaspending_api/recipient/management/sql/restock_recipient_profile.sql
  usaspending_api/transactions/agnostic_transaction_loader.py
  usaspending_api/transactions/delta_models/transaction_fabs.py
Labels: ready for review, work in progress
