Repository fedspendingtransparency/usaspending-api, pull requests merged in 2022-11, with the labels that each got.

#3623 [PIPE-442] transaction_search_gold TABLE_SPEC
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/management/commands/load_table_to_delta.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/transactions/delta_models/__init__.py
  usaspending_api/transactions/delta_models/transaction_search.py
Labels: do not merge, in progress

#3625 Initial work on moving transaction loaders to Spark
  usaspending_api/broker/lookups.py
  usaspending_api/etl/management/commands/load_transactions_in_delta.py
  usaspending_api/etl/migrations/0004_create_transaction_id_seq.py
  usaspending_api/etl/migrations/0005_create_award_id_seq.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/etl/tests/integration/test_load_transactions_in_delta.py
Labels: in progress

#3650 [DEV-9269] Subaward Spending Over Time Hotfix
  usaspending_api/search/v2/views/spending_over_time.py
Labels: hotfix

#3647 Initial work for transaction_f[ab|pd]s handlers for delta transaction loader code
  usaspending_api/common/data_classes.py
  usaspending_api/etl/management/commands/load_table_to_delta.py
  usaspending_api/etl/management/commands/load_transactions_in_delta.py
  usaspending_api/etl/tests/integration/test_load_transactions_in_delta.py
  usaspending_api/transactions/delta_models/transaction_fabs.py
  usaspending_api/transactions/delta_models/transaction_fpds.py
Labels: in progress
