Repository fedspendingtransparency/usaspending-api, pull requests merged in 2023-07, with the labels that each got.

#3854 [DEV-10007] County data update [hotfix]
  usaspending_api/references/management/commands/load_population_data.py
  usaspending_api/references/management/commands/load_reference_data.py
  usaspending_api/references/tests/data/census_2020_population_county.csv
  usaspending_api/references/tests/test_load_population_data.py
Labels: hotfix

#3860 [DEV-10017] Congressional districts update [hotfix][staging]
  usaspending_api/references/management/commands/load_population_data.py
  usaspending_api/references/management/commands/load_reference_data.py
  usaspending_api/references/tests/data/census_2021_population_congressional_district.csv
  usaspending_api/references/tests/test_load_population_data.py
Labels: hotfix, ready for review

#3863 [DEV-10017] Add support for CD code 90 [hotfix][staging]
  usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
  usaspending_api/search/tests/integration/test_spending_by_geography.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py
Labels: hotfix

#3862 [DEV-10017] Congressional districts update [hotfix][master]
  usaspending_api/references/management/commands/load_population_data.py
  usaspending_api/references/management/commands/load_reference_data.py
  usaspending_api/references/tests/data/census_2020_population_county.csv
  usaspending_api/references/tests/data/census_2021_population_congressional_district.csv
  usaspending_api/references/tests/test_load_population_data.py
  usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
  usaspending_api/search/tests/integration/test_spending_by_geography.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py
Labels: hotfix

#3859 [DEV-10007] County data update [hotfix][master]
  usaspending_api/references/management/commands/load_population_data.py
  usaspending_api/references/management/commands/load_reference_data.py
  usaspending_api/references/tests/data/census_2020_population_county.csv
  usaspending_api/references/tests/test_load_population_data.py
Labels: hotfix

#3861 [DEV-10017] Congressional districts update [hotfix][qat]
  usaspending_api/references/management/commands/load_population_data.py
  usaspending_api/references/management/commands/load_reference_data.py
  usaspending_api/references/tests/data/census_2020_population_county.csv
  usaspending_api/references/tests/data/census_2021_population_congressional_district.csv
  usaspending_api/references/tests/test_load_population_data.py
  usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
  usaspending_api/search/tests/integration/test_spending_by_geography.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py
Labels: hotfix

#3858 [DEV-10007] County data update [hotfix][qat]
  usaspending_api/references/management/commands/load_population_data.py
  usaspending_api/references/management/commands/load_reference_data.py
  usaspending_api/references/tests/data/census_2020_population_county.csv
  usaspending_api/references/tests/test_load_population_data.py
Labels: hotfix

#3877 [Warmfix] Skip Dummy Records in Bureau CSV
  usaspending_api/data/testing_data/FMS_GWA_EXPORT_APPN.csv
  usaspending_api/references/management/commands/load_bureau_title_lookup.py
Labels: warmfix

#3878 [Warmfix] Skip Dummy Records in Bureau CSV [master]
  usaspending_api/data/testing_data/FMS_GWA_EXPORT_APPN.csv
  usaspending_api/references/management/commands/load_bureau_title_lookup.py
Labels: warmfix
