Repository fedspendingtransparency/usaspending-api, pull requests merged in 2023-09, with the labels that each got.

#3909 [PIPE-496][DEV-10173] Copy Data From Delta to Postgres Fix; Additional Data Dictionary Logging
  usaspending_api/common/csv_stream_s3_to_pg.py
  usaspending_api/common/helpers/s3_helpers.py
  usaspending_api/common/tests/data/test_csv_stream_s3_to_pg_data.csv
  usaspending_api/common/tests/integration/test_csv_stream_s3_to_pg.py
  usaspending_api/common/tests/unit/test_csv_stream_s3_to_pg.py
  usaspending_api/download/filestreaming/download_generation.py
  usaspending_api/settings.py
Labels: do not merge, in progress, warmfix

#3911 [PIPE-496][DEV-10173][HOTFIX] Copy Data From Delta to Postgres Fix; Additional Data Dictionary Logging
  usaspending_api/common/csv_stream_s3_to_pg.py
  usaspending_api/common/helpers/s3_helpers.py
  usaspending_api/common/tests/data/test_csv_stream_s3_to_pg_data.csv
  usaspending_api/common/tests/integration/test_csv_stream_s3_to_pg.py
  usaspending_api/common/tests/unit/test_csv_stream_s3_to_pg.py
  usaspending_api/download/filestreaming/download_generation.py
  usaspending_api/settings.py
Labels: hotfix

#3923 [DEV-10238] Python3.8 upgrade
  .env.template
  .pre-commit-config.yaml
  .travis.yml
  Dockerfile
  Dockerfile.spark
  Makefile
  README.md
  pyproject.toml
  setup.py
Labels: ready for review

#3924 [DEV-9966] Remove Deprecated District Filter Term
  usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md
  usaspending_api/api_contracts/contracts/v2/download/awards.md
  usaspending_api/api_contracts/search_filters.md
  usaspending_api/awards/tests/unit/test_location_filter_geocode.py
  usaspending_api/awards/v2/filters/location_filter_geocode.py
  usaspending_api/awards/v2/filters/sub_award.py
  usaspending_api/common/helpers/generic_helper.py
  usaspending_api/common/query_with_filters.py
  usaspending_api/common/validator/award_filter.py
  usaspending_api/download/v2/download_transaction_count.py
  usaspending_api/download/v2/request_validations.py
  usaspending_api/search/tests/integration/test_spending_over_time.py
  usaspending_api/search/v2/views/spending_by_award.py
  usaspending_api/search/v2/views/spending_by_award_count.py
  usaspending_api/search/v2/views/spending_by_category.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_category.py
  usaspending_api/search/v2/views/spending_by_geography.py
  usaspending_api/search/v2/views/spending_over_time.py
Labels: ready for review

#3921 DEV-10143: Update SubawardSearch w/ County Cols
  usaspending_api/awards/tests/data/subaward.json
  usaspending_api/etl/tests/integration/test_load_to_from_delta_subawards.py
  usaspending_api/search/delta_models/subaward_search.py
  usaspending_api/search/migrations/0037_auto_20230921_1657.py
  usaspending_api/search/models/subaward_search.py
Labels: ready for review
