Repository fedspendingtransparency/usaspending-api, pull requests merged in 2023-03, with the labels that each got.

#3733 [DEV-9568] File B Downloads - USSGL 4802 Fields Fix
  usaspending_api/disaster/management/sql/disaster_covid19_file_b.sql
  usaspending_api/download/helpers/download_annotation_functions.py
  usaspending_api/download/v2/download_column_historical_lookups.py
Labels: warmfix

#3739 [HOTFIX] Using award_search instead of fabs
  usaspending_api/common/helpers/orm_helpers.py
  usaspending_api/download/helpers/download_annotation_functions.py
Labels: hotfix

#3748 [HOTFIX] Use Django extra() to join ES downloads to download_job_lookup
  usaspending_api/download/helpers/elasticsearch_download_functions.py
  usaspending_api/settings.py
Labels: hotfix

#3751 [HOTFIX] Join AwardSearch directly to TransactionSearch
  usaspending_api/awards/tests/test_transactions.py
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/download/helpers/download_annotation_functions.py
  usaspending_api/download/helpers/elasticsearch_download_functions.py
  usaspending_api/download/v2/download_column_historical_lookups.py
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/search/migrations/0030_force_as_linkage_to_ts.py
  usaspending_api/search/models/award_search.py
Labels: hotfix

#3671 [PIPE-236] Replace Tests
  usaspending_api/awards/models/transaction_fabs.py
  usaspending_api/awards/models/transaction_fpds.py
  usaspending_api/awards/models/transaction_normalized.py
  usaspending_api/awards/tests/test_awards_v2.py
  usaspending_api/disaster/tests/fixtures/agency_count_data.py
  usaspending_api/disaster/tests/fixtures/cfda_data.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/recipient_count_data.py
  usaspending_api/disaster/tests/fixtures/recipient_location_data.py
  usaspending_api/disaster/tests/integration/test_cfda_loans.py
  usaspending_api/disaster/tests/integration/test_cfda_spending.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_count.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_loans.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/tests/integration/test_disaster_recipient_count.py
  usaspending_api/disaster/tests/integration/test_recipient_loans.py
  usaspending_api/disaster/tests/integration/test_recipient_spending.py
  usaspending_api/disaster/tests/integration/test_spending_by_geography.py
  usaspending_api/disaster/v2/views/elasticsearch_base.py
  usaspending_api/download/tests/integration/test_download_contract.py
  usaspending_api/download/tests/integration/test_download_disaster.py
  usaspending_api/download/tests/integration/test_download_disaster_recipient.py
  usaspending_api/download/tests/integration/test_download_transactions.py
  usaspending_api/etl/award_helpers.py
  usaspending_api/etl/management/commands/touch_last_period_awards.py
  usaspending_api/etl/management/commands/update_missing_covid_awards.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta_subawards.py
  usaspending_api/etl/tests/integration/test_swap_in_new_table.py
  usaspending_api/etl/tests/integration/test_touch_last_period_awards.py
  usaspending_api/etl/tests/integration/test_touch_old_awards_for_es.py
  usaspending_api/idvs/tests/test_awards_idv_v2.py
  usaspending_api/search/tests/data/spending_by_award_test_data.py
  usaspending_api/search/tests/integration/hierarchical_filters/tas_fixtures.py
  usaspending_api/search/tests/integration/hierarchical_filters/test_tas_filter_basic_cases.py
  usaspending_api/search/tests/integration/hierarchical_filters/test_tas_filter_heirarchical_cases.py
  usaspending_api/search/tests/integration/hierarchical_filters/test_tas_filter_hybrid_cases.py
  usaspending_api/search/tests/integration/hierarchical_filters/test_tas_filter_irregular_formats.py
  usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
  usaspending_api/search/tests/integration/test_spending_by_award.py
  usaspending_api/search/tests/integration/test_spending_by_award_type.py
  usaspending_api/search/tests/integration/test_spending_by_award_type_count.py
  usaspending_api/search/tests/integration/test_spending_over_time.py
  usaspending_api/spending_explorer/tests/integration/test_spending_explorer.py
  usaspending_api/tests/test_demo_elasticsearch_tests.py
Labels: ready for review

#3755 [DEV-9553] Current Congressional Fields Infrastructure
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/database_scripts/etl/transaction_delta_view.sql
  usaspending_api/etl/elasticsearch_loader_helpers/aggregate_key_functions.py
  usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
  usaspending_api/etl/es_award_template.json
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/search/migrations/0032_as_ts_cur_congressional_codes.py
  usaspending_api/search/models/award_search.py
  usaspending_api/search/models/transaction_search.py
  usaspending_api/transactions/delta_models/transaction_search.py
Labels: ready for review

#3765 [DEV-9339][DEV-8925] IIJA/Covid Download Updates (WARMFIX)
  usaspending_api/bulk_download/tests/test_download.py
  usaspending_api/disaster/management/sql/disaster_covid19_file_d1_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_d2_awards.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_contracts.sql
  usaspending_api/disaster/management/sql/disaster_covid19_file_f_grants.sql
  usaspending_api/download/helpers/download_annotation_functions.py
  usaspending_api/download/tests/integration/test_populate_monthly_delta_files.py
  usaspending_api/download/tests/integration/test_populate_monthly_files.py
  usaspending_api/download/v2/download_column_historical_lookups.py
Labels: warmfix
