Repository fedspendingtransparency/usaspending-api, pull requests merged in 2023-11, with the labels that each got.

#3961 [DEV-10362] Adds --skip-file-c-to-d-linkage Flag to Submission Loaders
  usaspending_api/etl/management/commands/load_multiple_submissions.py
  usaspending_api/etl/management/commands/load_submission.py
  usaspending_api/etl/submission_loader_helpers/file_c.py
  usaspending_api/etl/tests/integration/test_load_submission_mgmt_cmd.py
Labels: warmfix

#3962 [DEV-10362] [WARMFIX] Logging - Skip C to D Linkage
  usaspending_api/etl/submission_loader_helpers/file_c.py
Labels: warmfix

#3963 [DEV-10362] [HOTFIX] Skip C to D Linkage Logic in Submission Loader
  usaspending_api/etl/management/commands/load_multiple_submissions.py
  usaspending_api/etl/management/commands/load_submission.py
  usaspending_api/etl/submission_loader_helpers/file_c.py
  usaspending_api/etl/tests/integration/test_load_submission_mgmt_cmd.py
Labels: hotfix

#3959 [DEV-9596] Update testing container
  .env.template
  Dockerfile.testing
  README.md
  docker-compose.yml
  usaspending_api/conftest.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/etl/tests/integration/test_spark_app.py
Labels: ready for review

#3966 [DEV-10384] Increases max nested objects limit to 12k on Covid FABA Index
  usaspending_api/etl/es_covid19_faba_template.json
Labels: hotfix

#3967 [DEV-10384][Staging] Increases max nested objects limit to 12k on Covid FABA Index
  usaspending_api/etl/es_covid19_faba_template.json
Labels: warmfix
