Repository fedspendingtransparency/usaspending-api, pull requests merged in 2023-01, with the labels that each got.

#3665 Award Search - Blank Recipient Level Fix
  usaspending_api/search/v2/views/spending_by_award.py
Labels: warmfix

#3679 Staging -> QAT Downmerge
  usaspending_api/agency/v2/views/sub_agency.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/tests/integration/test_disaster_def_code_count.py
  usaspending_api/disaster/tests/integration/test_disaster_federal_account_count.py
  usaspending_api/disaster/tests/integration/test_disaster_object_class_count.py
  usaspending_api/search/v2/views/spending_by_award.py
Labels: down merge

#3657 [PIPE-339] Handle transaction_normalized ETL level in Spark transaction loader
  usaspending_api/broker/helpers/build_business_categories_boolean_dict.py
  usaspending_api/broker/helpers/get_business_categories.py
  usaspending_api/broker/helpers/last_load_date.py
  usaspending_api/broker/helpers/upsert_fabs_transactions.py
  usaspending_api/common/data_classes.py
  usaspending_api/etl/management/commands/load_table_to_delta.py
  usaspending_api/etl/management/commands/load_transactions_in_delta.md
  usaspending_api/etl/management/commands/load_transactions_in_delta.py
  usaspending_api/etl/tests/integration/test_load_transactions_in_delta.py
  usaspending_api/etl/transaction_loaders/data_load_helpers.py
  usaspending_api/transactions/delta_models/__init__.py
  usaspending_api/transactions/delta_models/transaction_fabs.py
  usaspending_api/transactions/delta_models/transaction_fpds.py
  usaspending_api/transactions/delta_models/transaction_normalized.py
Labels: in progress

#3683 [DEV-9040] Fix bug in custom account downloads
  usaspending_api/accounts/tests/unit/test_account_download_mappings.py
  usaspending_api/accounts/v2/filters/account_download.py
  usaspending_api/download/helpers/download_annotation_functions.py
  usaspending_api/download/lookups.py
  usaspending_api/download/v2/download_column_historical_lookups.py
Labels: warmfix, ready for review

#3686 [PIPE-340] Fix casing when merging broker fabs
  usaspending_api/awards/migrations/0099_auto_20230113_1858.py
  usaspending_api/common/etl/postgres/operations.py
  usaspending_api/transactions/agnostic_transaction_loader.py
  usaspending_api/transactions/management/commands/transfer_assistance_records.py
  usaspending_api/transactions/management/commands/transfer_procurement_records.py
  usaspending_api/transactions/models/source_assistance_transaction.py
  usaspending_api/transactions/tests/integration/test_assistance_etl.py
Labels: ready for review

#3676 [PIPE-347] Spark-based elasticsearch_indexer
  .env.template
  .travis.yml
  usaspending_api/common/csv_stream_s3_to_pg.py
  usaspending_api/common/etl/spark.py
  usaspending_api/common/helpers/generic_helper.py
  usaspending_api/common/helpers/spark_helpers.py
  usaspending_api/common/management/commands/matview_runner.py
  usaspending_api/common/matview_manager.py
  usaspending_api/config/envs/default.py
  usaspending_api/config/utils.py
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/database_scripts/matviews/vw_es_award_search.sql
  usaspending_api/etl/elasticsearch_loader_helpers/__init__.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/extract_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/utilities.py
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
  usaspending_api/etl/management/commands/elasticsearch_indexer_for_spark.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
  usaspending_api/etl/tests/unit/elasticsearch_loader_helpers/test_controller.py
Labels: ready for review
