Repository fedspendingtransparency/usaspending-api, pull requests merged in 2023-08, with the labels that each got.

#3886 [DEV-10125] Fix country code field name [warmfix][QAT]
  usaspending_api/api_docs/templatetags/docs.py
  usaspending_api/search/v2/views/spending_by_geography.py
Labels: warmfix

#3889 [DEV-10149] Removes Unnecessary Award Updates from Postgres C to D Linkage Code
  .travis.yml
  usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_fain.sql
  usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_fain_and_uri.sql
  usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_piid.sql
  usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_uri.sql
  usaspending_api/submissions/management/commands/rm_submission.py
Labels: warmfix

#3890 [DEV-10149][Master] Removes Unnecessary Award Updates from Postgres C to D Linkage Code
  .travis.yml
  usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_fain.sql
  usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_fain_and_uri.sql
  usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_piid.sql
  usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_uri.sql
  usaspending_api/submissions/management/commands/rm_submission.py
Labels: hotfix

#3891 [DEV-10128] Add countries to search/spending_by_geography endpoint
  usaspending_api/api_contracts/contracts/v2/search/spending_by_geography.md
  usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_country.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_recipient.py
  usaspending_api/search/tests/integration/test_spending_by_geography.py
  usaspending_api/search/v2/views/spending_by_geography.py
Labels: ready for review

#3907 [DEV-10183] Update search/spending_by_geography endpoint to support domestic and foreign countries
  usaspending_api/api_contracts/contracts/v2/search/spending_by_geography.md
  usaspending_api/search/tests/integration/test_spending_by_geography.py
  usaspending_api/search/v2/views/spending_by_geography.py
Labels: ready for review
