Repository fedspendingtransparency/usaspending-api, pull requests merged in 2023-10, with the labels that each got.

#3927 [DEV-10158] File C to D linkage performance improvements
  usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_fain.sql
  usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_fain_and_uri.sql
  usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_piid.sql
  usaspending_api/etl/management/sql/c_file_linkage/update_file_c_linkages_uri.sql
Labels: ready for review

#3925 [DEV-9596] Add testing libraries to support usaspending-test container
  Dockerfile.testing
  README.md
  docker-compose.yml
Labels: ready for review

#3941 [DEV-10317] Update domestic place_of_performance ES query [hotfix][staging]
  usaspending_api/common/query_with_filters.py
  usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_recipient.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_state_territory.py
  usaspending_api/search/tests/integration/test_spending_by_geography.py
Labels: hotfix, ready for review

#3942 [DEV-10317] Update domestic place_of_performance ES query [hotfix][master]
  usaspending_api/common/query_with_filters.py
  usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_recipient.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_state_territory.py
  usaspending_api/search/tests/integration/test_spending_by_geography.py
Labels: hotfix

#3944 [PIPE-509] Reduce Calls to load-transactions-in-delta Django Command
  usaspending_api/etl/management/commands/load_transactions_in_delta.py
  usaspending_api/etl/tests/integration/test_load_transactions_in_delta.py
  usaspending_api/etl/tests/unit/test_load_transactions_in_delta.py
Labels: ready for review

#3943 [DEV-10317] Update domestic place_of_performance ES query [hotfix][qat]
  usaspending_api/common/query_with_filters.py
  usaspending_api/search/tests/integration/spending_by_category/spending_test_fixtures.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_recipient.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_state_territory.py
  usaspending_api/search/tests/integration/test_spending_by_geography.py
Labels: hotfix
