Repository fedspendingtransparency/usaspending-api, pull requests merged in 2024-03, with the labels that each got.

#4041 [DEV-10453] Fix Spark dictionary error
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
Labels: warmfix

#4048 [DEV-10756] update config files [DEV-10745] update library imports
  .env.template
  .pre-commit-config.yaml
  .travis.yml
  Dockerfile
  Dockerfile.spark
  Makefile
  README.md
  requirements/requirements-app.txt
  requirements/requirements-dev.txt
  setup.py
  usaspending_api/awards/v2/data_layer/orm_utils.py
  usaspending_api/conftest.py
Labels: do not merge

#4053 [DEV-8150] Fix agency name sorting on agency disaster spending and agencies overview endpoints
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/v2/views/elasticsearch_account_base.py
  usaspending_api/reporting/tests/integration/test_agencies_overview.py
  usaspending_api/reporting/v2/views/agencies/overview.py
Labels: ready for review

#3996 [PIPE-513] Copied Data to Postgres Incrementally
  usaspending_api/broker/helpers/last_delta_table_load_version.py
  usaspending_api/broker/lookups.py
  usaspending_api/broker/management/commands/load_broker_static_data.py
  usaspending_api/broker/migrations/0003_deltatableloadversion.py
  usaspending_api/broker/models.py
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/management/commands/load_table_from_delta.py
  usaspending_api/etl/management/commands/load_table_to_delta.py
  usaspending_api/etl/management/commands/swap_in_new_table.py
  usaspending_api/etl/tests/integration/test_load_to_from_delta.py
  usaspending_api/etl/tests/integration/test_model.py
  usaspending_api/search/delta_models/award_search.py
Labels: do not merge

#4058 [DEV-8150] Sort the award spending by sub-agency results alphabetically
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/v2/views/agency/spending.py
Labels: ready for review

#4042 [DEV-10453] Fix Spark dictionary error [warmfix][qat]
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
Labels: warmfix

#4059 Sprint 183 QAT -> Staging
  dredd-results.txt
  usaspending_api/api_contracts/contracts/v2/search/spending_by_transaction.md
  usaspending_api/disaster/tests/integration/test_disaster_agency_spending.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/elasticsearch_account_base.py
  usaspending_api/reporting/tests/integration/test_agencies_overview.py
  usaspending_api/reporting/v2/views/agencies/overview.py
Labels: ready for review
