Repository fedspendingtransparency/usaspending-api, pull requests merged in 2024-01, with the labels that each got.

#3990 [DEV-10555][Master] Increases nested objects limit to 25k on Covid Index
  usaspending_api/etl/es_covid19_faba_template.json
Labels: hotfix

#3991 [DEV-10555][Staging] Increases nested objects limit to 25k on Covid Index
  usaspending_api/etl/es_covid19_faba_template.json
Labels: warmfix

#3984 [DEV-10427] Add an Elasticsearch Index for Recipients
  usaspending_api/common/elasticsearch/search_wrappers.py
  usaspending_api/conftest.py
  usaspending_api/conftest_helpers.py
  usaspending_api/database_scripts/etl/recipient_profile_delta_view.sql
  usaspending_api/etl/elasticsearch_loader_helpers/__init__.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller_for_spark.py
  usaspending_api/etl/elasticsearch_loader_helpers/index_config.py
  usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
  usaspending_api/etl/es_recipient_profile_template.json
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
  usaspending_api/etl/management/commands/es_configure.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
  usaspending_api/search/tests/data/utilities.py
  usaspending_api/settings.py
Labels: ready for review

#3998 [DEV-10427] Recipient Profile Spark controller update
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller_for_spark.py
Labels: ready for review
