Repository fedspendingtransparency/usaspending-api, pull requests merged in 2024-04, with the labels that each got.

#4063 [DEV-10834] Increase the nested_object.limit value for the covid19-faba index [hotfix][master]
  usaspending_api/etl/es_covid19_faba_template.json
Labels: hotfix

#4064 [DEV-10834] Increase the nested_object.limit value for the covid19-faba index [hotfix][qat]
  usaspending_api/etl/es_covid19_faba_template.json
  usaspending_api/references/management/commands/load_offices.py
Labels: hotfix, ready for review

#4069 [DEV-9234] Use is_final_balances_for_fy instead of final_of_fy for total_budgetary_resources calculations
  usaspending_api/accounts/tests/integration/test_federal_account_v2.py
  usaspending_api/accounts/views/federal_accounts_v2.py
Labels: ready for review

#4071 [DEV-9633] Use latest_transaction_search instead of latest_transaction
  usaspending_api/spending_explorer/v2/filters/spending_filter.py
Labels: ready for review

#4052 [DEV-10748] Fix for psycopg2.errors.InvalidCursorName while running tests
  usaspending_api/awards/migrations/0104_alter_transactiondelta_transaction.py
  usaspending_api/references/migrations/0067_alter_office_office_code.py
  usaspending_api/search/migrations/0041_alter_awardsearch_award_alter_summarystateview_duh.py
  usaspending_api/settings.py
  usaspending_api/submissions/migrations/0016_alter_dabssubmissionwindowschedule_id.py
Labels: do not merge
