Repository fedspendingtransparency/usaspending-api, pull requests merged in 2024-02, with the labels that each got.

#4000 DEV-10558: Initial work for CFDA -> AssistanceListing
  usaspending_api/awards/delta_models/broker_subawards.py
  usaspending_api/awards/tests/data/subaward.json
  usaspending_api/search/delta_models/subaward_search.py
  usaspending_api/transactions/delta_models/published_fabs.py
  usaspending_api/transactions/delta_models/transaction_fabs.py
  usaspending_api/transactions/migrations/0010_auto_20240126_1915.py
  usaspending_api/transactions/models/source_assistance_transaction.py
  usaspending_api/transactions/tests/integration/test_assistance_etl.py
Labels: ready for review

#4005 [DEV-10558] CFDA -> AssistanceListing (Downmerge QAT <- Staging)
  usaspending_api/awards/delta_models/broker_subawards.py
  usaspending_api/awards/tests/data/subaward.json
  usaspending_api/search/delta_models/subaward_search.py
  usaspending_api/transactions/delta_models/published_fabs.py
  usaspending_api/transactions/delta_models/transaction_fabs.py
  usaspending_api/transactions/migrations/0010_auto_20240126_1915.py
  usaspending_api/transactions/models/source_assistance_transaction.py
  usaspending_api/transactions/tests/integration/test_assistance_etl.py
Labels: ready for review

#3970 [DEV-10292] Add location autocomplete API Contract
  usaspending_api/api_contracts/contracts/v2/autocomplete/location.md
Labels: do not merge, ready for review

#4015 Constrain uWSGI version
  requirements/requirements-server.txt
Labels: hotfix
