Repository fedspendingtransparency/usaspending-api, pull requests merged in 2024-09, with the labels that each got.

#4177 [DEV-11299] Set the current CD to 00 for single congressional district states
  usaspending_api/transactions/delta_models/transaction_current_cd_lookup.py
Labels: ready for review

#4178 [DEV-11406]: List Database Download Update [hotfix] [staging]
  usaspending_api/config/envs/local.py
  usaspending_api/config/envs/production.py
  usaspending_api/download/helpers/download_file_helpers.py
  usaspending_api/download/v2/list_database_downloads.py
  usaspending_api/download/v2/list_unlinked_awards_downloads.py
Labels: hotfix, ready for review

#4180 [DEV-10630] Autocomplete recipient partial search
  usaspending_api/references/tests/integration/test_recipients_autocomplete_v2.py
  usaspending_api/references/v2/views/recipients.py
Labels: ready for review

#4179 [DEV-11422] Updated the query to calculate total_outlays
  usaspending_api/recipient/tests/integration/test_state.py
  usaspending_api/search/migrations/0044_remove_summarystateview_action_date.py
  usaspending_api/search/models/summary_state_view.py
  usaspending_api/transactions/delta_models/summary_state_view.py
Labels: ready for review

#4181 Dev 11406 listdatabasedownload [hotfix][master]
  usaspending_api/config/envs/local.py
  usaspending_api/config/envs/production.py
  usaspending_api/download/helpers/download_file_helpers.py
  usaspending_api/download/v2/list_database_downloads.py
  usaspending_api/download/v2/list_unlinked_awards_downloads.py
Labels: hotfix

#4173 [Dev-11261] rename data act broker to data accountability broker
  README.md
  data_reformatting.md
  loading_data.md
  usaspending_api/accounts/migrations/0006_rename_column_data_source.py
  usaspending_api/awards/migrations/0104_rename_column_data_source.py
  usaspending_api/awards/models/award.py
  usaspending_api/broker/management/commands/derive_office_names.py
  usaspending_api/common/models.py
  usaspending_api/data/COVID-19_download_readme.txt
  usaspending_api/etl/management/commands/load_fpds_csv.py
  usaspending_api/etl/management/commands/load_submission.py
  usaspending_api/etl/management/load_base.py
  usaspending_api/etl/submission_loader_helpers/file_a.py
  usaspending_api/financial_activities/migrations/0009_rename_column_data_source.py
  usaspending_api/references/management/commands/load_tas.py
  usaspending_api/references/migrations/0067_rename_column_data_source.py
  usaspending_api/settings.py
Labels: ready for review

#4182 Dev 11406 listdatabasedownload [hotfix][qat]
  usaspending_api/config/envs/local.py
  usaspending_api/config/envs/production.py
  usaspending_api/download/helpers/download_file_helpers.py
  usaspending_api/download/v2/list_database_downloads.py
  usaspending_api/download/v2/list_unlinked_awards_downloads.py
  usaspending_api/settings.py
Labels: hotfix

#4192 [DEV-11406] Add DATABASE_DOWNLOAD_S3_BUCKET_NAME config to all environments
  usaspending_api/config/envs/production.py
  usaspending_api/config/envs/qat.py
  usaspending_api/config/envs/sandbox.py
  usaspending_api/config/envs/staging.py
Labels: ready for review

#4198 [DEV-11487] Index update_date on award_search [hotfix][staging]
  usaspending_api/search/migrations/0045_index_update_date_on_award_search.py
  usaspending_api/search/models/award_search.py
Labels: hotfix, ready for review

#4200 [DEV-11487] Index update_date on award_search [hotfix][master]
  usaspending_api/search/migrations/0045_index_update_date_on_award_search.py
  usaspending_api/search/models/award_search.py
Labels: hotfix, ready for review

#4201 [DEV-11487] Index update_date on award_search
  usaspending_api/search/migrations/0045_index_update_date_on_award_search.py
  usaspending_api/search/models/award_search.py
Labels: ready for review

#4199 [DEV-11421] Update the USASpending API Dockerfile
  Dockerfile
  Dockerfile-Server
Labels: ready for review
