Repository fedspendingtransparency/usaspending-api, pull requests merged in 2025-03, with the labels that each got.

#4299 [DEV-12248] Update Award ID query for Subawards [hotfix][staging]
  usaspending_api/common/query_with_filters.py
  usaspending_api/search/tests/integration/hierarchical_filters/test_tas_filter_basic_cases_subaward.py
  usaspending_api/search/tests/integration/test_spending_by_award.py
Labels: hotfix, ready for review

#4301 [DEV-12248] Update Award ID query for Subawards [hotfix][prod]
  usaspending_api/common/query_with_filters.py
  usaspending_api/search/tests/integration/hierarchical_filters/test_tas_filter_basic_cases_subaward.py
  usaspending_api/search/tests/integration/test_spending_by_award.py
Labels: do not merge, hotfix, ready for review

#4302 [DEV-12248] Update Award ID query for Subawards [hotfix][qat]
  usaspending_api/common/query_with_filters.py
  usaspending_api/search/tests/integration/hierarchical_filters/test_tas_filter_basic_cases_subaward.py
  usaspending_api/search/tests/integration/test_spending_by_award.py
Labels: hotfix, ready for review

#4306 [DEV-12261] - Fix check awards for deletes to escape special characters
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/utilities.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
Labels: hotfix, ready for review

#4307 Promote Hotfixes
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/utilities.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
  usaspending_api/search/delta_models/subaward_search.py
  usaspending_api/search/migrations/0052_alter_subawardsearch_subaward_report_month_and_more.py
  usaspending_api/search/models/subaward_search.py
Labels: hotfix, ENV Promotion

#4309 Remove pyspark import and infer schema
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
Labels: hotfix

#4310 Remove pyspark import and infer schema
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
Labels: hotfix

#4308 Downmerge into QAT
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/utilities.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
  usaspending_api/search/delta_models/subaward_search.py
  usaspending_api/search/migrations/0052_alter_subawardsearch_subaward_report_month_and_more.py
  usaspending_api/search/models/subaward_search.py
Labels: down merge

#4311 Downmerge into QAT
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
Labels: down merge

#4314 Preventing null value for sub_action_date and subaward_amount
  usaspending_api/search/delta_models/subaward_search.py
Labels: hotfix

#4315 [Prod] Subaward search handle null sub action date
  usaspending_api/search/delta_models/subaward_search.py
Labels: hotfix

#4316 [Downmerge] Subaward search handle null sub action date
  usaspending_api/search/delta_models/subaward_search.py
Labels: down merge

#4298 [DEV-12144] Update location ES index structure and add foreign cities
  usaspending_api/api_contracts/contracts/v2/autocomplete/location.md
  usaspending_api/conftest_helpers.py
  usaspending_api/database_scripts/etl/location_delta_view.sql
  usaspending_api/etl/elasticsearch_loader_helpers/__init__.py
  usaspending_api/etl/elasticsearch_loader_helpers/aggregate_key_functions.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller_for_spark.py
  usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/utilities.py
  usaspending_api/etl/es_location_template.json
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
  usaspending_api/references/tests/integration/test_location_autocomplete_v2.py
  usaspending_api/references/v2/views/location_autocomplete.py
Labels: ready for review

#4321 [DEV-11927] Update recipient_id description on API contracts where present
  usaspending_api/api_contracts/contracts/v2/download/count.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_agency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_subagency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/cfda.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/country.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/county.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/defc.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/district.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/federal_account.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_agency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_subagency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/naics.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/psc.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/recipient.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/recipient_duns.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/state_territory.md
Labels: ready for review

#4313 [DEV-12237] - Update Spending by Transaction Grouped
  .codeclimate.yml
  usaspending_api/api_contracts/contracts/v2/search/spending_by_transaction_grouped.md
  usaspending_api/api_docs/markdown/endpoints.md
  usaspending_api/search/tests/integration/test_spending_by_transaction_grouped.py
  usaspending_api/search/v2/urls.py
  usaspending_api/search/v2/views/search_elasticsearch.py
  usaspending_api/search/v2/views/spending_by_transaction_grouped.py
Labels: ready for review

#4323 [DEV-12144] Replace `named_struct` with `map` for Databricks
  usaspending_api/etl/elasticsearch_loader_helpers/controller_for_spark.py
Labels: ready for review

#4325 [DEV-12144] Add missing location_type key for `United States` [hotfix][staging]
  usaspending_api/database_scripts/etl/location_delta_view.sql
  usaspending_api/references/tests/integration/test_location_autocomplete_v2.py
Labels: hotfix, ready for review

#4326 [DEV-12144] Add missing location_type key for United States [hotfix][qat]
  usaspending_api/database_scripts/etl/location_delta_view.sql
  usaspending_api/references/tests/integration/test_location_autocomplete_v2.py
Labels: ready for review, down merge

#4211 Updating README and local config
  .env.template
  .gitignore
  CONTRIBUTING.md
  Dockerfile
  Dockerfile.spark
  Dockerfile.testing
  Makefile
  README.md
  docker-compose.yml
  pyproject.toml
  usaspending_api/common/helpers/spark_helpers.py
  usaspending_api/config/envs/local.py
  usaspending_api/conftest.py
  usaspending_api/tests/conftest_spark.py
Labels: ready for review
