Repository fedspendingtransparency/usaspending-api, pull requests merged in 2025-02, with the labels that each got.

#4264 Update subaward ES test setup
  usaspending_api/common/tests/integration/test_subawards_elasticsearch_query.py
  usaspending_api/conftest_helpers.py
Labels: ready for review

#4266 Sprint 198 Staging deploy
  usaspending_api/common/tests/integration/test_subawards_elasticsearch_query.py
  usaspending_api/conftest_helpers.py
Labels: ENV Promotion

#4268 update-transaction-number-of-shards
  usaspending_api/etl/es_transaction_template.json
Labels: hotfix

#4272 Downmerge into Staging
  usaspending_api/etl/es_transaction_template.json
Labels: down merge

#4269 [DEV-12006] Update recipient ES query [hotfix][staging]
  usaspending_api/etl/es_recipient_profile_template.json
  usaspending_api/references/tests/integration/test_recipients_autocomplete_v2.py
  usaspending_api/references/v2/views/recipients.py
Labels: hotfix, ready for review

#4275 Update monthly delta files command [hotfix][staging]
  usaspending_api/download/management/commands/populate_monthly_delta_files.py
Labels: hotfix, ready for review

#4274 Sprint 198 Prod deploy
  usaspending_api/common/tests/integration/test_subawards_elasticsearch_query.py
  usaspending_api/conftest_helpers.py
  usaspending_api/download/management/commands/populate_monthly_delta_files.py
  usaspending_api/etl/es_recipient_profile_template.json
  usaspending_api/references/tests/integration/test_recipients_autocomplete_v2.py
  usaspending_api/references/v2/views/recipients.py
Labels: ready for review, ENV Promotion

#4273 Downmerge in QAT
  usaspending_api/etl/es_transaction_template.json
Labels: down merge

#4278 [DEV-12096] Fix populate monthly delta command [hotfix][QAT]
  usaspending_api/download/management/commands/populate_monthly_delta_files.py
Labels: hotfix, ready for review, down merge

#4262 [DEV-11590] Update locations autocomplete results
  usaspending_api/api_contracts/contracts/v2/autocomplete/location.md
  usaspending_api/database_scripts/etl/location_delta_view.sql
  usaspending_api/etl/es_location_template.json
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
  usaspending_api/references/tests/integration/test_location_autocomplete_v2.py
  usaspending_api/references/tests/unit/test_location_autocomplete_formatters.py
  usaspending_api/references/v2/views/location_autocomplete.py
Labels: ready for review

#4279 Calculating the number of slices that should be used for deleting
  usaspending_api/conftest_helpers.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/load_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/utilities.py
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
Labels: do not merge, hotfix

#4276 [DEV-11552] Add outlays to spending by category endpoints
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_agency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_subagency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/cfda.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/country.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/county.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/defc.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/district.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/federal_account.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_agency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_subagency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/naics.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/psc.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/recipient.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/recipient_duns.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/state_territory.md
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_awarding_agency.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_awarding_subagency.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_cfda.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_country.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_county.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_district.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_federal_account.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_funding_agency.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_funding_subagency.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_naics.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_psc.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_recipient.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_state_territory.py
  usaspending_api/search/tests/integration/test_spending_by_category_categories.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_agency_types.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_category.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_federal_account.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_industry_codes.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_recipient.py
Labels: ready for review

#4281 Downmerge Slice Calculation to Staging
  usaspending_api/conftest_helpers.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/load_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/utilities.py
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
Labels: down merge

#4286 [DEV-12084] Fix File B Calculations
  usaspending_api/accounts/views/federal_accounts_v2.py
  usaspending_api/accounts/views/financial_spending.py
  usaspending_api/agency/tests/integration/conftest.py
  usaspending_api/agency/tests/integration/test_agency_budget_function.py
  usaspending_api/agency/tests/integration/test_agency_federal_account_list.py
  usaspending_api/agency/tests/integration/test_agency_object_class_list.py
  usaspending_api/agency/tests/integration/test_agency_program_activity_list.py
  usaspending_api/agency/tests/integration/test_agency_tas_object_class.py
  usaspending_api/agency/tests/integration/test_agency_tas_program_activity.py
  usaspending_api/agency/v2/views/budget_function.py
  usaspending_api/agency/v2/views/budget_function_count.py
  usaspending_api/agency/v2/views/budgetary_resources.py
  usaspending_api/agency/v2/views/bureau_federal_account.py
  usaspending_api/agency/v2/views/federal_account_count.py
  usaspending_api/agency/v2/views/federal_account_list.py
  usaspending_api/agency/v2/views/object_class_count.py
  usaspending_api/agency/v2/views/object_class_list.py
  usaspending_api/agency/v2/views/program_activity_count.py
  usaspending_api/agency/v2/views/program_activity_list.py
  usaspending_api/agency/v2/views/subcomponents.py
  usaspending_api/agency/v2/views/tas_object_class_list.py
  usaspending_api/agency/v2/views/tas_program_activity_list.py
  usaspending_api/common/calculations/file_b.py
  usaspending_api/common/tests/integration/test_calculations_for_file_b.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/def_code/count.py
  usaspending_api/disaster/v2/views/federal_account/count.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/object_class/count.py
  usaspending_api/disaster/v2/views/object_class/spending.py
  usaspending_api/reporting/management/sql/populate_reporting_agency_tas.sql
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_tas.py
  usaspending_api/spending_explorer/tests/integration/test_spending_explorer.py
  usaspending_api/spending_explorer/v2/filters/explorer.py
  usaspending_api/spending_explorer/v2/filters/type_filter.py
Labels: hotfix

#4282 Downmerge slice calculations to QAT
  usaspending_api/conftest_helpers.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/load_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/utilities.py
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
Labels: ready for review, down merge

#4263 [DEV-11772] Create a new django command for spark download using a query
  docker-compose.yml
  usaspending_api/common/helpers/download_csv_strategies.py
  usaspending_api/common/helpers/s3_helpers.py
  usaspending_api/config/envs/local.py
  usaspending_api/download/delta_models/__init__.py
  usaspending_api/download/filestreaming/download_generation.py
  usaspending_api/download/management/__init__.py
  usaspending_api/download/management/commands/__init__.py
  usaspending_api/download/management/commands/delta_downloads/__init__.py
  usaspending_api/download/management/commands/delta_downloads/award_financial/__init__.py
  usaspending_api/download/management/commands/delta_downloads/award_financial/federal_account.py
  usaspending_api/download/management/commands/generate_spark_download.py
Labels: ready for review

#4287 Deploy File B Calculation Hotfix to Prod
  usaspending_api/accounts/views/federal_accounts_v2.py
  usaspending_api/accounts/views/financial_spending.py
  usaspending_api/agency/tests/integration/conftest.py
  usaspending_api/agency/tests/integration/test_agency_budget_function.py
  usaspending_api/agency/tests/integration/test_agency_federal_account_list.py
  usaspending_api/agency/tests/integration/test_agency_object_class_list.py
  usaspending_api/agency/tests/integration/test_agency_program_activity_list.py
  usaspending_api/agency/tests/integration/test_agency_tas_object_class.py
  usaspending_api/agency/tests/integration/test_agency_tas_program_activity.py
  usaspending_api/agency/v2/views/budget_function.py
  usaspending_api/agency/v2/views/budget_function_count.py
  usaspending_api/agency/v2/views/budgetary_resources.py
  usaspending_api/agency/v2/views/bureau_federal_account.py
  usaspending_api/agency/v2/views/federal_account_count.py
  usaspending_api/agency/v2/views/federal_account_list.py
  usaspending_api/agency/v2/views/object_class_count.py
  usaspending_api/agency/v2/views/object_class_list.py
  usaspending_api/agency/v2/views/program_activity_count.py
  usaspending_api/agency/v2/views/program_activity_list.py
  usaspending_api/agency/v2/views/subcomponents.py
  usaspending_api/agency/v2/views/tas_object_class_list.py
  usaspending_api/agency/v2/views/tas_program_activity_list.py
  usaspending_api/common/calculations/file_b.py
  usaspending_api/common/tests/integration/test_calculations_for_file_b.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/def_code/count.py
  usaspending_api/disaster/v2/views/federal_account/count.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/object_class/count.py
  usaspending_api/disaster/v2/views/object_class/spending.py
  usaspending_api/reporting/management/sql/populate_reporting_agency_tas.sql
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_tas.py
  usaspending_api/spending_explorer/tests/integration/test_spending_explorer.py
  usaspending_api/spending_explorer/v2/filters/explorer.py
  usaspending_api/spending_explorer/v2/filters/type_filter.py
Labels: hotfix

#4288 Downmerge File B fixes to QAT
  usaspending_api/accounts/views/federal_accounts_v2.py
  usaspending_api/accounts/views/financial_spending.py
  usaspending_api/agency/tests/integration/conftest.py
  usaspending_api/agency/tests/integration/test_agency_budget_function.py
  usaspending_api/agency/tests/integration/test_agency_federal_account_list.py
  usaspending_api/agency/tests/integration/test_agency_object_class_list.py
  usaspending_api/agency/tests/integration/test_agency_program_activity_list.py
  usaspending_api/agency/tests/integration/test_agency_tas_object_class.py
  usaspending_api/agency/tests/integration/test_agency_tas_program_activity.py
  usaspending_api/agency/v2/views/budget_function.py
  usaspending_api/agency/v2/views/budget_function_count.py
  usaspending_api/agency/v2/views/budgetary_resources.py
  usaspending_api/agency/v2/views/bureau_federal_account.py
  usaspending_api/agency/v2/views/federal_account_count.py
  usaspending_api/agency/v2/views/federal_account_list.py
  usaspending_api/agency/v2/views/object_class_count.py
  usaspending_api/agency/v2/views/object_class_list.py
  usaspending_api/agency/v2/views/program_activity_count.py
  usaspending_api/agency/v2/views/program_activity_list.py
  usaspending_api/agency/v2/views/subcomponents.py
  usaspending_api/agency/v2/views/tas_object_class_list.py
  usaspending_api/agency/v2/views/tas_program_activity_list.py
  usaspending_api/common/calculations/file_b.py
  usaspending_api/common/tests/integration/test_calculations_for_file_b.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/def_code/count.py
  usaspending_api/disaster/v2/views/federal_account/count.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/object_class/count.py
  usaspending_api/disaster/v2/views/object_class/spending.py
  usaspending_api/reporting/management/sql/populate_reporting_agency_tas.sql
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_tas.py
  usaspending_api/spending_explorer/tests/integration/test_spending_explorer.py
  usaspending_api/spending_explorer/v2/filters/explorer.py
  usaspending_api/spending_explorer/v2/filters/type_filter.py
Labels: ready for review, down merge

#4265 [DEV-11770] [DEV-11771] - Add account_download create and load commands, Add generate spark download command
  .travis.yml
  usaspending_api/accounts/views/federal_accounts_v2.py
  usaspending_api/accounts/views/financial_spending.py
  usaspending_api/agency/tests/integration/conftest.py
  usaspending_api/agency/tests/integration/test_agency_budget_function.py
  usaspending_api/agency/tests/integration/test_agency_federal_account_list.py
  usaspending_api/agency/tests/integration/test_agency_object_class_list.py
  usaspending_api/agency/tests/integration/test_agency_program_activity_list.py
  usaspending_api/agency/tests/integration/test_agency_tas_object_class.py
  usaspending_api/agency/tests/integration/test_agency_tas_program_activity.py
  usaspending_api/agency/v2/views/budget_function.py
  usaspending_api/agency/v2/views/budget_function_count.py
  usaspending_api/agency/v2/views/budgetary_resources.py
  usaspending_api/agency/v2/views/bureau_federal_account.py
  usaspending_api/agency/v2/views/federal_account_count.py
  usaspending_api/agency/v2/views/federal_account_list.py
  usaspending_api/agency/v2/views/object_class_count.py
  usaspending_api/agency/v2/views/object_class_list.py
  usaspending_api/agency/v2/views/program_activity_count.py
  usaspending_api/agency/v2/views/program_activity_list.py
  usaspending_api/agency/v2/views/subcomponents.py
  usaspending_api/agency/v2/views/tas_object_class_list.py
  usaspending_api/agency/v2/views/tas_program_activity_list.py
  usaspending_api/common/calculations/file_b.py
  usaspending_api/common/helpers/download_csv_strategies.py
  usaspending_api/common/helpers/s3_helpers.py
  usaspending_api/common/tests/integration/test_calculations_for_file_b.py
  usaspending_api/config/envs/local.py
  usaspending_api/conftest_helpers.py
  usaspending_api/disaster/v2/views/agency/spending.py
  usaspending_api/disaster/v2/views/def_code/count.py
  usaspending_api/disaster/v2/views/federal_account/count.py
  usaspending_api/disaster/v2/views/federal_account/spending.py
  usaspending_api/disaster/v2/views/object_class/count.py
  usaspending_api/disaster/v2/views/object_class/spending.py
  usaspending_api/download/delta_models/account_download.py
  usaspending_api/download/filestreaming/download_generation.py
  usaspending_api/download/management/__init__.py
  usaspending_api/download/management/commands/__init__.py
  usaspending_api/download/management/commands/delta_downloads/__init__.py
  usaspending_api/download/management/commands/delta_downloads/award_financial/__init__.py
  usaspending_api/download/management/commands/delta_downloads/award_financial/federal_account.py
  usaspending_api/download/management/commands/generate_spark_download.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/load_data.py
  usaspending_api/etl/elasticsearch_loader_helpers/utilities.py
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
  usaspending_api/reporting/management/sql/populate_reporting_agency_tas.sql
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_tas.py
  usaspending_api/spending_explorer/tests/integration/test_spending_explorer.py
  usaspending_api/spending_explorer/v2/filters/explorer.py
  usaspending_api/spending_explorer/v2/filters/type_filter.py
  usaspending_api/transactions/delta_models/transaction_search.py
Labels: ready for review

#4290 [DEV-11465] Change spending_by_geography to use Elasticsearch for Subawards
  usaspending_api/common/elasticsearch/search_wrappers.py
  usaspending_api/etl/elasticsearch_loader_helpers/aggregate_key_functions.py
  usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
  usaspending_api/etl/es_subaward_template.json
  usaspending_api/search/tests/data/spending_by_geography_spending_level_data.py
  usaspending_api/search/tests/integration/test_spending_by_geography.py
  usaspending_api/search/tests/integration/test_spending_by_geography_city.py
  usaspending_api/search/v2/elasticsearch_helper.py
  usaspending_api/search/v2/views/spending_by_geography.py
Labels: ready for review

#4291 [DEV-11606] Increment max search date
  usaspending_api/settings.py
Labels: ready for review

#4295 [DEV-11464] Update delta SQL for subaward prime_award_recipient_id
  usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
  usaspending_api/search/delta_models/subaward_search.py
  usaspending_api/search/v2/views/spending_by_award.py
Labels: ready for review
