Repository fedspendingtransparency/usaspending-api, pull requests merged in 2025-04, with the labels that each got.

#4332 Ftr/dev 12287 new spending by award fields
  usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/search/migrations/0053_awardsearch_pop_zip4_and_more.py
  usaspending_api/search/models/award_search.py
  usaspending_api/search/tests/data/spending_by_award_test_data.py
  usaspending_api/search/tests/integration/test_spending_by_award.py
  usaspending_api/search/v2/views/spending_by_award.py
Labels: ready for review

#4336 [DEV-12290] add unique award id for transaction filter
  usaspending_api/api_contracts/contracts/v2/search/spending_by_transaction.md
  usaspending_api/common/helpers/api_helper.py
  usaspending_api/common/query_with_filters.py
  usaspending_api/search/tests/integration/test_spending_by_transaction.py
Labels: ready for review

#4327 [DEV-11466] Update spending_by_category endpoints to use Elasticsearch for subawards
  usaspending_api/database_scripts/etl/subaward_es_view.sql
  usaspending_api/etl/elasticsearch_loader_helpers/aggregate_key_functions.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller_for_spark.py
  usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
  usaspending_api/etl/es_subaward_template.json
  usaspending_api/search/delta_models/subaward_search.py
  usaspending_api/search/helpers/spending_by_category_helpers.py
  usaspending_api/search/migrations/0054_add_columns_for_es_agg_keys.py
  usaspending_api/search/models/subaward_search.py
  usaspending_api/search/tests/integration/test_spending_by_category_categories.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_agency_types.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_category.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_federal_account.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_industry_codes.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_recipient.py
Labels: ready for review

#4339 [DEV-12376] Updated ES delete logging and corrected use of pipeline timestamp
  usaspending_api/broker/helpers/last_load_date.py
  usaspending_api/common/helpers/s3_helpers.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
  usaspending_api/etl/tests/integration/test_es_deletes_pre_fy2008.py
Labels: hotfix, ready for review

#4343 Hotfixes for Pipeline Deletes
  usaspending_api/broker/helpers/last_load_date.py
  usaspending_api/common/helpers/s3_helpers.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
  usaspending_api/etl/tests/integration/test_es_deletes_pre_fy2008.py
  usaspending_api/transactions/management/commands/delete_assistance_records.py
  usaspending_api/transactions/tests/integration/test_assistance_etl.py
  usaspending_api/transactions/tests/integration/test_procurement_etl.py
Labels: hotfix, ready for review

#4345 Downmerge delete hotfixes into QAT
  usaspending_api/broker/helpers/last_load_date.py
  usaspending_api/common/helpers/s3_helpers.py
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
  usaspending_api/etl/elasticsearch_loader_helpers/delete_data.py
  usaspending_api/etl/tests/integration/test_elasticsearch_indexer.py
  usaspending_api/etl/tests/integration/test_es_deletes_pre_fy2008.py
  usaspending_api/transactions/management/commands/delete_assistance_records.py
  usaspending_api/transactions/tests/integration/test_assistance_etl.py
  usaspending_api/transactions/tests/integration/test_procurement_etl.py
Labels: down merge

#4346 [DEV-12266] Fix subaward count and total logic setting wrong values
  usaspending_api/etl/management/commands/update_delta_award_with_subaward_counts.py
  usaspending_api/etl/tests/integration/test_update_delta_award_with_subaward_counts.py
  usaspending_api/tests/conftest_spark.py
Labels: ready for review

#4350 Ftr/dev 12288/add elements to spending by transaction
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/search/tests/integration/test_spending_by_transaction.py
  usaspending_api/search/v2/views/search_elasticsearch.py
Labels: ready for review

#4351 QAT -> Staging Promotion
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/search/tests/integration/test_spending_by_transaction.py
  usaspending_api/search/v2/views/search_elasticsearch.py
Labels: ENV Promotion

#4355 [DEV-12424] Change to only a single DB query - Staging
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_funding_agency.py
  usaspending_api/search/tests/integration/test_spending_by_category_categories.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_agency_types.py
Labels: hotfix

#4354 [DEV-12424] Change to only a single DB query
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_funding_agency.py
  usaspending_api/search/tests/integration/test_spending_by_category_categories.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_agency_types.py
Labels: hotfix

#4357 Downmerge Staging to QAT
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_funding_agency.py
  usaspending_api/search/tests/integration/test_spending_by_category_categories.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_agency_types.py
Labels: down merge

#4360 [DEV-12478] Update location autocomplete to limit by location_type [hotfix][staging]
  usaspending_api/api_contracts/contracts/v2/autocomplete/location.md
  usaspending_api/references/tests/integration/test_location_autocomplete_v2.py
  usaspending_api/references/v2/views/location_autocomplete.py
Labels: hotfix, ready for review

#4361 [DEV-12478] Update location autocomplete to limit by location_type [hotfix][master]
  usaspending_api/api_contracts/contracts/v2/autocomplete/location.md
  usaspending_api/references/tests/integration/test_location_autocomplete_v2.py
  usaspending_api/references/v2/views/location_autocomplete.py
Labels: hotfix, ready for review

#4363 [DEV-12478] Update location autocomplete to limit by location_type [hotfix][qat]
  usaspending_api/api_contracts/contracts/v2/autocomplete/location.md
  usaspending_api/references/tests/integration/test_location_autocomplete_v2.py
  usaspending_api/references/v2/views/location_autocomplete.py
Labels: ready for review, down merge

#4368 Set the slice count for deletes on the Transaction Index to 1
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
Labels: hotfix

#4364 [DEV-12503] Fix typo in county_fips SQL
  usaspending_api/database_scripts/etl/location_delta_view.sql
Labels: ready for review

#4367 [DEV-12286] Handle null recipient hash and level
  usaspending_api/search/v2/views/spending_by_award.py
Labels: ready for review

#4356 Ftr/dev 9490 spending explorer not responding
  usaspending_api/awards/migrations/0110_financialaccountsbyawards_faba_treasury_submission_idx_and_more.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
  usaspending_api/spending_explorer/v2/filters/explorer.py
Labels: ready for review

#4370 [DEV-12286] Fix error when subaward fields are NULL
  usaspending_api/search/v2/views/spending_by_award.py
Labels: ready for review

#4373 Downmerge slice count change to QAT
  usaspending_api/etl/elasticsearch_loader_helpers/controller.py
Labels: down merge

#4371 [DEV-11599] Remove outdated comment that referenced DAIMS
  usaspending_api/download/v2/download_column_historical_lookups.py
Labels: ready for review

#4374 Ftr/dev 12455 update sorting for awards
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/etl/es_award_template.json
  usaspending_api/search/tests/data/spending_by_award_test_data.py
  usaspending_api/search/tests/integration/test_spending_by_award.py
  usaspending_api/search/v2/views/spending_by_award.py
Labels: ready for review

#4376 Ftr/dev 12456 update sorting for subawards
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/etl/es_subaward_template.json
  usaspending_api/recipient/tests/integration/test_state.py
  usaspending_api/search/tests/data/spending_by_award_test_data.py
  usaspending_api/search/tests/integration/test_spending_by_award.py
  usaspending_api/search/v2/views/spending_by_award.py
Labels: ready for review

#4380 [DEV-10281] remove object_class from search endpoint api contracts
  usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_transaction.md
  usaspending_api/api_contracts/contracts/v2/search/spending_over_time.md
  usaspending_api/search/v2/views/spending_by_award.py
Labels: ready for review

#4378 Ftr/dev 12421 update sorting for transactions
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/search/tests/integration/test_spending_by_transaction.py
  usaspending_api/search/v2/views/search_elasticsearch.py
Labels: ready for review
