Repository fedspendingtransparency/usaspending-api, pull requests merged in 2025-01, with the labels that each got.

#4251 [DEV-11876] Update PARK field names
  usaspending_api/accounts/tests/integration/test_federal_account_v2.py
  usaspending_api/agency/tests/integration/conftest.py
  usaspending_api/agency/tests/integration/test_agency_budgetary_resources.py
  usaspending_api/agency/tests/integration/test_agency_tas_program_activity.py
  usaspending_api/agency/tests/integration/test_subcomponents.py
  usaspending_api/awards/migrations/0108_stage_renamed_park_columns_faba.py
  usaspending_api/awards/migrations/0109_delete_old_park_columns_faba.py
  usaspending_api/awards/models/financial_accounts_by_awards.py
  usaspending_api/common/calculations/file_b.py
  usaspending_api/common/tests/integration/test_calculations_for_file_b.py
  usaspending_api/database_scripts/job_archive/backfill_renamed_park_fields.py
  usaspending_api/disaster/tests/fixtures/disaster_account_data.py
  usaspending_api/disaster/tests/fixtures/federal_account_data.py
  usaspending_api/disaster/tests/fixtures/object_class_data.py
  usaspending_api/etl/submission_loader_helpers/file_b.py
  usaspending_api/financial_activities/migrations/0012_stage_renamed_park_columns_fabpaoc.py
  usaspending_api/financial_activities/migrations/0013_delete_old_park_columns_fabpaoc.py
  usaspending_api/financial_activities/models.py
  usaspending_api/references/tests/integration/test_financial_spending.py
  usaspending_api/reporting/management/sql/populate_reporting_agency_tas.sql
  usaspending_api/reporting/tests/integration/test_populate_reporting_agency_tas.py
  usaspending_api/spending_explorer/tests/integration/test_spending_explorer.py
Labels: ready for review

#4250 [DEV-11398] - Separate categories for awards and transactions
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_agency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_subagency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/cfda.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/country.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/county.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/defc.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/district.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/federal_account.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_agency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_subagency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/naics.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/psc.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/recipient.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/recipient_duns.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/state_territory.md
  usaspending_api/database_scripts/etl/award_delta_view.sql
  usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
  usaspending_api/etl/es_award_template.json
  usaspending_api/etl/es_transaction_template.json
  usaspending_api/search/delta_models/award_search.py
  usaspending_api/search/migrations/0049_awardsearch_federal_accounts.py
  usaspending_api/search/models/award_search.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_awarding_agency.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_awarding_subagency.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_cfda.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_country.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_county.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_defc.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_district.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_federal_account.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_funding_agency.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_funding_subagency.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_naics.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_psc.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_recipient.py
  usaspending_api/search/tests/integration/spending_by_category/test_spending_by_state_territory.py
  usaspending_api/search/tests/integration/test_spending_by_category_categories.py
  usaspending_api/search/v2/views/enums.py
  usaspending_api/search/v2/views/spending_by_category.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_category.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_industry_codes.py
  usaspending_api/search/v2/views/spending_by_category_views/spending_by_locations.py
  usaspending_api/search/v2/views/spending_by_geography.py
  usaspending_api/tests/conftest_spark.py
Labels: ready for review

#4252 [DEV-11551] - Award Description Filter
  usaspending_api/api_contracts/contracts/v2/search/spending_by_award.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_award_count.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_agency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/awarding_subagency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/cfda.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/country.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/county.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/defc.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/district.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/federal_account.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_agency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/funding_subagency.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/naics.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/psc.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/recipient.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/recipient_duns.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_category/state_territory.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_geography.md
  usaspending_api/api_contracts/contracts/v2/search/spending_by_transaction.md
  usaspending_api/api_contracts/contracts/v2/search/spending_over_time.md
  usaspending_api/awards/tests/integration/test_subaward_filter.py
  usaspending_api/awards/v2/filters/sub_award.py
  usaspending_api/common/query_with_filters.py
  usaspending_api/common/tests/integration/test_query_with_filters.py
  usaspending_api/common/validator/award_filter.py
  usaspending_api/common/validator/tests/unit/test_tinyshield.py
  usaspending_api/search/v2/views/spending_by_geography.py
Labels: ready for review

#4254 [DEV-11489] Convert program activities JSON to dictionary for Elasticsearch indexer
  usaspending_api/etl/elasticsearch_loader_helpers/__init__.py
  usaspending_api/etl/elasticsearch_loader_helpers/transform_data.py
  usaspending_api/etl/management/commands/elasticsearch_indexer.py
Labels: ready for review

#4256 Fix Makefile and remove project imports from python script
  Makefile
  usaspending_api/database_scripts/job_archive/backfill_renamed_park_fields.py
Labels: warmfix

#4258 [DEV-11489] Fix typo in Subaward ES view
  usaspending_api/database_scripts/etl/subaward_es_view.sql
Labels: warmfix

#4257 Downmerge for Cleanup python script and makefile
  Makefile
  usaspending_api/database_scripts/job_archive/backfill_renamed_park_fields.py
Labels: down merge

#4259 [Down merge] Fix typo in Subaward ES view
  usaspending_api/database_scripts/etl/subaward_es_view.sql
Labels: down merge
