Repository fedspendingtransparency/usaspending-api, pull requests merged in 2025-07, with the labels that each got.

#4428 [DEV-12574] - Additional Dynamic Filters for Account Downloads
  usaspending_api/api_contracts/contracts/v2/download/accounts.md
  usaspending_api/download/delta_models/account_download.py
  usaspending_api/download/management/commands/delta_downloads/award_financial/builders.py
  usaspending_api/download/management/commands/delta_downloads/award_financial/filters.py
  usaspending_api/download/management/commands/generate_spark_download.py
  usaspending_api/download/tests/integration/test_account_download_dataframe_builder.py
  usaspending_api/download/tests/integration/test_account_download_filter.py
Labels: ready for review

#4435 QAT -> Staging Promotion
  .github/pull_request_template.md
  .github/pull_request_template_future.md
  .github/workflows/pull-request-and-review-updates.yaml
  README.md
  usaspending_api/awards/management/commands/generate_unlinked_awards_download.py
  usaspending_api/broker/management/commands/update_table_value_from_broker.py
  usaspending_api/disaster/management/commands/generate_covid19_download.py
Labels: ENV Promotion

#4438 [DEV-12873] Add recipient_id to spending_by_transaction
  usaspending_api/api_contracts/contracts/v2/search/spending_by_transaction.md
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/search/tests/integration/test_spending_by_transaction.py
  usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
  usaspending_api/search/v2/elasticsearch_helper.py
  usaspending_api/search/v2/urls.py
  usaspending_api/search/v2/views/search_elasticsearch.py
  usaspending_api/search/v2/views/spending_by_transaction.py
  usaspending_api/search/v2/views/spending_by_transaction_count.py
  usaspending_api/search/v2/views/transaction_spending_summary.py
Labels: ready for review

#4443 [DEV-12878] Create delta table for File B custom account downloads
  .github/workflows/code-climate-before-build.yaml
  .github/workflows/code-climate-report-coverage.yaml
  .github/workflows/pull-request-checks.yaml
  usaspending_api/download/delta_models/object_class_program_activity_download.py
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/tests/integration/test_create_delta_table.py
Labels: ready for review

#4446 Sprint 206 Prod Deploy
  .github/workflows/code-climate-before-build.yaml
  .github/workflows/code-climate-report-coverage.yaml
  .github/workflows/pull-request-checks.yaml
  setup.cfg
  usaspending_api/api_contracts/contracts/v2/search/spending_by_transaction.md
  usaspending_api/awards/v2/lookups/elasticsearch_lookups.py
  usaspending_api/common/helpers/download_csv_strategies.py
  usaspending_api/common/query_with_filters.py
  usaspending_api/common/spark/configs.py
  usaspending_api/database_scripts/etl/subaward_es_view.sql
  usaspending_api/download/delta_models/account_download.py
  usaspending_api/download/delta_models/object_class_program_activity_download.py
  usaspending_api/download/management/commands/delta_downloads/award_financial/__init__.py
  usaspending_api/download/management/commands/delta_downloads/award_financial/builders.py
  usaspending_api/download/management/commands/delta_downloads/award_financial/columns.py
  usaspending_api/download/management/commands/delta_downloads/builders.py
  usaspending_api/download/management/commands/delta_downloads/filters.py
  usaspending_api/download/management/commands/generate_spark_download.py
  usaspending_api/download/tests/integration/test_account_download_dataframe_builder.py
  usaspending_api/download/tests/integration/test_account_download_filter.py
  usaspending_api/etl/es_subaward_template.json
  usaspending_api/etl/management/commands/load_query_to_delta.py
  usaspending_api/etl/tests/integration/test_create_delta_table.py
  usaspending_api/search/tests/integration/test_spending_by_award.py
  usaspending_api/search/tests/integration/test_spending_by_transaction.py
  usaspending_api/search/tests/unit/test_elasticsearch_helpers.py
  usaspending_api/search/v2/elasticsearch_helper.py
  usaspending_api/search/v2/urls.py
  usaspending_api/search/v2/views/search_elasticsearch.py
  usaspending_api/search/v2/views/spending_by_award.py
  usaspending_api/search/v2/views/spending_by_transaction.py
  usaspending_api/search/v2/views/spending_by_transaction_count.py
  usaspending_api/search/v2/views/transaction_spending_summary.py
Labels: ready for review, ENV Promotion
